package Transicao;

import Funcoes.Dates;
import Funcoes.Db;
import Funcoes.FuncoesGlobais;
import Funcoes.LerValor;
import Funcoes.VariaveisGlobais;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author supervisor
 */
public class jPagar extends javax.swing.JPanel {
    public static String vrDOCTO = "0,00";
    private int tpOPC  = 0;
    public float vrAREC = 0;
    private boolean jbt = true;
    public boolean bprintdoc = false;
    public String rgprp = "", rgimv = "", contrato = "", operacao = "DEB", acao = "";
    static Db conn = VariaveisGlobais.conexao;

    /** Creates new form jReceber */
    public jPagar() {
        initComponents();

        FlatSVGIcon DisabledIconeDN = new FlatSVGIcon("icons/dinheiro.svg",98,43);        
        FlatSVGIcon iconeDN = new FlatSVGIcon("icons/dinheiro.svg",98,43);        
        iconeDN.setColorFilter(new FlatSVGIcon.ColorFilter(color -> { return Color.GREEN; }));        

        FlatSVGIcon DisabledIconeCH = new FlatSVGIcon("icons/cheque.svg",98,43);        
        FlatSVGIcon iconeCH = new FlatSVGIcon("icons/cheque.svg",98,43);        
        iconeCH.setColorFilter(new FlatSVGIcon.ColorFilter(color -> { return Color.RED; }));        

        FlatSVGIcon DisabledIconeCT = new FlatSVGIcon("icons/banco.svg",98,33);        
        FlatSVGIcon iconeCT = new FlatSVGIcon("icons/banco.svg",98,33);        
        iconeCT.setColorFilter(new FlatSVGIcon.ColorFilter(color -> { return Color.BLUE; }));        
        
        jtgDN.setIcon(iconeDN);
        jtgDN.setDisabledIcon(DisabledIconeDN);
        jtgDN.setDisabledSelectedIcon(DisabledIconeDN);
        jtgDN.setSelectedIcon(iconeDN);
        
        jtgCH.setIcon(iconeCH);
        jtgCH.setDisabledIcon(DisabledIconeCH);
        jtgCH.setDisabledSelectedIcon(DisabledIconeCH);
        jtgCH.setSelectedIcon(iconeCH);
        
        jtgCT.setIcon(iconeCT);
        jtgCT.setDisabledIcon(DisabledIconeCT);
        jtgCT.setDisabledSelectedIcon(DisabledIconeCT);
        jtgCT.setSelectedIcon(iconeCT);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jfmCT = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jfmBC = new javax.swing.JFormattedTextField(3);
        jLabel7 = new javax.swing.JLabel();
        jfmAG = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jfmCH = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jfmDT = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel10 = new javax.swing.JLabel();
        jfmVRCH = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jfmVRDN = new javax.swing.JFormattedTextField();
        jbtLancar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRESTO = new javax.swing.JFormattedTextField();
        jTROCO = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtgDN = new javax.swing.JToggleButton();
        jlbDN = new javax.swing.JLabel();
        jtgCH = new javax.swing.JToggleButton();
        jlbCH = new javax.swing.JLabel();
        jtgCT = new javax.swing.JToggleButton();
        jlbCT = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(456, 268));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel1.setName("jpnDigite"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(385, 280));

        jLabel5.setText("Número");

        jfmCT.setEnabled(false);
        jfmCT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfmCTFocusGained(evt);
            }
        });

        jLabel6.setText("Banco:");

        jfmBC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("000"))));
        jfmBC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfmBC.setText("000");
        jfmBC.setEnabled(false);
        jfmBC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfmBCFocusGained(evt);
            }
        });

        jLabel7.setText("Agência:");

        jfmAG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0000"))));
        jfmAG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfmAG.setText("0000");
        jfmAG.setEnabled(false);
        jfmAG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfmAGFocusGained(evt);
            }
        });

        jLabel8.setText("Cheque:");

        jfmCH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("000000"))));
        jfmCH.setText("000000");
        jfmCH.setEnabled(false);
        jfmCH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfmCHFocusGained(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Data:");

        jfmDT.setDate(new java.util.Date(-2208977612000L));
        jfmDT.setEnabled(false);

        jLabel10.setText("Valor Cheque:");

        jfmVRCH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jfmVRCH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jfmVRCH.setText("0,00");
        jfmVRCH.setEnabled(false);
        jfmVRCH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfmVRCHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfmVRCHFocusLost(evt);
            }
        });

        jLabel11.setText("Valor Dinheiro:");

        jfmVRDN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jfmVRDN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jfmVRDN.setText("0,00");
        jfmVRDN.setEnabled(false);
        jfmVRDN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfmVRDNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfmVRDNFocusLost(evt);
            }
        });

        jbtLancar.setText("Lançar");
        jbtLancar.setName("jbtLancar"); // NOI18N
        jbtLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLancarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.setName("jbtCancelar"); // NOI18N

        jLabel12.setText("RESTA:");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("TROCO:");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRESTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jRESTO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jRESTO.setText("0,00");
        jRESTO.setDisabledTextColor(new java.awt.Color(51, 153, 0));
        jRESTO.setEnabled(false);
        jRESTO.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRESTO.setName("jRESTO"); // NOI18N
        jRESTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRESTOActionPerformed(evt);
            }
        });

        jTROCO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jTROCO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTROCO.setText("0,00");
        jTROCO.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        jTROCO.setEnabled(false);
        jTROCO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Digite");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtLancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfmVRDN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfmCT)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jfmCH, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfmDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jfmBC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfmAG, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addComponent(jfmVRCH)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRESTO)
                            .addComponent(jTROCO, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmCT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmBC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmAG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jfmCH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmDT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmVRCH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmVRDN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtCancelar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtLancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRESTO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTROCO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setName("pnlBotoes"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FORMA");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);

        jtgDN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_dn_bw.jpg"))); // NOI18N
        jtgDN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtgDN.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_dn_bw.jpg"))); // NOI18N
        jtgDN.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_dn_bw.jpg"))); // NOI18N
        jtgDN.setName("jtgDN"); // NOI18N
        jtgDN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_dn.jpg"))); // NOI18N
        jtgDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtgDNActionPerformed(evt);
            }
        });

        jlbDN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDN.setText("Dinheiro");
        jlbDN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jlbDN.setOpaque(true);

        jtgCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ch_bw.jpg"))); // NOI18N
        jtgCH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtgCH.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ch_bw.jpg"))); // NOI18N
        jtgCH.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ch_bw.jpg"))); // NOI18N
        jtgCH.setName("jtgCH"); // NOI18N
        jtgCH.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ch.jpg"))); // NOI18N
        jtgCH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtgCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtgCHActionPerformed(evt);
            }
        });

        jlbCH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCH.setText("Cheque");
        jlbCH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jlbCH.setOpaque(true);

        jtgCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ct_bw.jpg"))); // NOI18N
        jtgCT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtgCT.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ct_bw.jpg"))); // NOI18N
        jtgCT.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ct_bw.jpg"))); // NOI18N
        jtgCT.setName("jtgCT"); // NOI18N
        jtgCT.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ct.jpg"))); // NOI18N
        jtgCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtgCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtgCTActionPerformed(evt);
            }
        });

        jlbCT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCT.setText("Banco");
        jlbCT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jlbCT.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtgCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtgCT)
            .addComponent(jlbCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlbCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlbDN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtgDN)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtgDN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbDN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtgCH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbCH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtgCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbCT))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jfmVRCHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmVRCHFocusGained
        float result = (LerValor.StringToFloat(jTROCO.getText()) * -1) + LerValor.StringToFloat(jRESTO.getText()) + LerValor.StringToFloat(jfmVRCH.getText());
        jRESTO.setValue(result);
        jTROCO.setValue(0);

        FuncoesGlobais.SelectAllInFormattedTextField(evt);
}//GEN-LAST:event_jfmVRCHFocusGained

    private void jfmVRCHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmVRCHFocusLost
        float result = LerValor.StringToFloat(jRESTO.getText()) - LerValor.StringToFloat(jfmVRCH.getText());
        if (result < 0) {
            final String BALLOON_TEXT = "<html><center>"
                    + "Lançamentos em Cheque <font color=red>NÃO</font> PODEM GERAR TROCO...<br>"
                    + "(Click para desaparecer este balloon)</center></html>";
//            BalloonTip tip = new BalloonTip(
//                    jfmVRCH, 
//                    new JLabel(BALLOON_TEXT),
//                    new RoundedBalloonStyle(5,5,Color.WHITE, Color.BLACK), 
//                    BalloonTip.Orientation.RIGHT_BELOW, 
//                    BalloonTip.AttachLocation.ALIGNED, 
//                    0, 
//                    5, 
//                    false);
//            ToolTipUtils.balloonToToolTip(tip, 500, 3000);
//            tip.show();

            jbtLancar.setEnabled(false);
            jTROCO.setValue(result * -1);
            jRESTO.setValue(0);
            jfmVRCH.requestFocus();
        } else { jRESTO.setValue(result); jTROCO.setValue(0); jbtLancar.setEnabled(true);}
}//GEN-LAST:event_jfmVRCHFocusLost

    private void jfmVRDNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmVRDNFocusGained
        float result = (LerValor.StringToFloat(jTROCO.getText()) * -1) + LerValor.StringToFloat(jRESTO.getText()) + LerValor.StringToFloat(jfmVRDN.getText());
        jRESTO.setValue(result);
        jTROCO.setValue(0);

        FuncoesGlobais.SelectAllInFormattedTextField(evt);
}//GEN-LAST:event_jfmVRDNFocusGained

    private void jfmVRDNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmVRDNFocusLost
        float result = LerValor.StringToFloat(jRESTO.getText()) - LerValor.StringToFloat(jfmVRDN.getText());
        if (result < 0) {
            jTROCO.setValue(result * -1);
            jRESTO.setValue(0);
            if (tpOPC == 3) {
                final String BALLOON_TEXT = "<html><center>"
                        + "Lançamentos em CARTÃO <font color=red>NÃO</font> PODEM GERAR TROCO...<br>"
                        + "(Click para desaparecer este balloon)</center></html>";
//                BalloonTip tip = new BalloonTip(
//                        jfmVRCH, 
//                        new JLabel(BALLOON_TEXT),
//                        new RoundedBalloonStyle(5,5,Color.WHITE, Color.BLACK), 
//                        BalloonTip.Orientation.RIGHT_BELOW, 
//                        BalloonTip.AttachLocation.ALIGNED, 
//                        0, 
//                        5, 
//                        false);
//                ToolTipUtils.balloonToToolTip(tip, 500, 3000);
//                tip.show();

                jbtLancar.setEnabled(false);
                jfmVRDN.requestFocus();
            } else jbtLancar.setEnabled(true);
        } else { jRESTO.setValue(result); jTROCO.setValue(0); jbtLancar.setEnabled(true);}
}//GEN-LAST:event_jfmVRDNFocusLost

    private void jtgDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtgDNActionPerformed
        Escolha(1);
}//GEN-LAST:event_jtgDNActionPerformed

    private void jtgCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtgCHActionPerformed
        Escolha(2);
}//GEN-LAST:event_jtgCHActionPerformed

    private void jtgCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtgCTActionPerformed
        Escolha(3);
}//GEN-LAST:event_jtgCTActionPerformed

    private void jRESTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRESTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRESTOActionPerformed

    private void jbtLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLancarActionPerformed
        
    }//GEN-LAST:event_jbtLancarActionPerformed

    private void jfmCTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmCTFocusGained
        jfmCT.setText("");
    }//GEN-LAST:event_jfmCTFocusGained

    private void jfmBCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmBCFocusGained
        jfmBC.setText("");
    }//GEN-LAST:event_jfmBCFocusGained

    private void jfmAGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmAGFocusGained
        jfmAG.setText("");
    }//GEN-LAST:event_jfmAGFocusGained

    private void jfmCHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmCHFocusGained
        jfmCH.setText("");
    }//GEN-LAST:event_jfmCHFocusGained

    public void Lancar() {
        // Cheque
        if (tpOPC == 2) {
            if (Integer.valueOf("0" + jfmBC.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "Você deve informar o Banco do Cheque !!!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                SwingUtilities.invokeLater(new Runnable(){ public void run(){ try{ jfmBC.requestFocus(true); }catch(Exception e){} } });                 
                return;
            }
            if (Integer.valueOf("0" + jfmAG.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "Você deve informar a Agencia do Cheque !!!", "Atenção", JOptionPane.INFORMATION_MESSAGE);                
                SwingUtilities.invokeLater(new Runnable(){ public void run(){ try{ jfmAG.requestFocus(true); }catch(Exception e){} } });                 
                return;
            }
            if (Integer.valueOf("0" + jfmCH.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "Você deve informar o Número do Cheque !!!", "Atenção", JOptionPane.INFORMATION_MESSAGE);                                
                SwingUtilities.invokeLater(new Runnable(){ public void run(){ try{ jfmCH.requestFocus(true); }catch(Exception e){} } });                 
                return;
            }
        } 
        
        // Banco
        if (tpOPC == 3) {
            if (Integer.valueOf("0" + jfmCT.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "Você deve informar o Número da Transação Bancária !!!", "Atenção", JOptionPane.INFORMATION_MESSAGE);                
                SwingUtilities.invokeLater(new Runnable(){ public void run(){ try{ jfmCT.requestFocus(true); }catch(Exception e){} } });                 
                return;
            }
        } 
        
        float result = LerValor.StringToFloat(jRESTO.getText());
        float digitar = 0;
        if (tpOPC == 1) { digitar = LerValor.StringToFloat(jfmVRDN.getText()); }
        if (tpOPC == 2) { digitar = LerValor.StringToFloat(jfmVRCH.getText()); }
        if (tpOPC == 3) { digitar = LerValor.StringToFloat(jfmVRDN.getText()); }

        //if (digitar > 0) {
            String sqlTxt = "INSERT INTO transicao (rgprp, rgimv, contrato, ncaixa, tipo, data, datapre, cartao, banco, " +
                         "agencia, cheque, vrcheque, vrdinheiro, operacao, acao) " +
                         "VALUES ('&1.','&2.','&3.','&4.','&5.','&6.','&7.','&8.','&9.','&10.','&11.','&12.','&13.','&14.','&15.')";

//            String dnLancar = LerValor.floatToCurrency(LerValor.StringToFloat(jfmVRDN.getText()) - LerValor.StringToFloat(jTROCO.getText()),2);
//            String dtpre = (jfmDT.getDate() == null ? "" : Dates.DateFormata("dd/MM/yyyy", jfmDT.getDate()));
            String dtpre = (jfmDT.getDate() == null ? "" : Dates.DateFormata("dd/MM/yyyy", jfmDT.getDate()));
            String dnLancar = LerValor.floatToCurrency(LerValor.StringToFloat(jfmVRDN.getText()) - LerValor.StringToFloat(jTROCO.getText()),2);

//            sqlTxt = FuncoesGlobais.Subst(sqlTxt, new String[] {
//                      rgprp,
//                      rgimv,
//                      contrato,
//                      VariaveisGlobais.usuario,
//                      (tpOPC == 1 ? "DN" : (tpOPC == 2 ? "CH" : "CT")),
//                      Dates.DateFormata("dd/MM/yyyy", new Date()),
//                      dtpre,
//                      jfmCT.getText().trim(),
//                      jfmBC.getText(), jfmAG.getText(), jfmCH.getText(),
//                      FuncoesGlobais.GravaValores(jfmVRCH.getText(),2),
//                      dnLancar,
//                      operacao, acao});
        sqlTxt = FuncoesGlobais.Subst(sqlTxt, new String[] {
                  rgprp,
                  rgimv,
                  contrato,
                  VariaveisGlobais.usuario,
                  (tpOPC == 1 ? "DN" : (tpOPC == 2 ? ("".equals(dtpre) ? "CH" : "CP") : "CT")),
                  Dates.DateFormata("dd/MM/yyyy", new Date()),
                  dtpre,
                  jfmCT.getText().trim(),
                  jfmBC.getText(), jfmAG.getText(), jfmCH.getText(),
                  FuncoesGlobais.GravaValores(jfmVRCH.getText(),2),
                  FuncoesGlobais.GravaValores(dnLancar,2),
                  operacao, acao});

            conn.CommandExecute(sqlTxt);
        //}

        if (result > 0 && digitar > 0) {
            if (tpOPC == 1) { jfmVRDN.setValue(0); jfmVRDN.requestFocus(); } else
            if (tpOPC == 2) { jfmVRCH.setValue(0); jfmBC.requestFocus(); } else
            if (tpOPC == 3) { jfmVRDN.setValue(0); jfmCT.setText(""); jfmCT.requestFocus(); }

            bprintdoc = false;
        } else {
            bprintdoc = true;
        }
    }

    public void LimpaTransicao() {
        String[] param = {VariaveisGlobais.usuario.trim(), acao};
        String sql = FuncoesGlobais.Subst("DELETE FROM transicao WHERE ncaixa = '&1.' AND acao = '&2.';", param);
        conn.CommandExecute(sql);
    }

    public boolean Cancelar() {
        boolean retorno = false;
        if (jbt) {
            Escolha(4);
            jRESTO.setValue(vrAREC); jTROCO.setValue(0);
            jbtCancelar.setEnabled(true);
            jbtLancar.setEnabled(false);
            bprintdoc = false;
            LimpaTransicao();
            retorno = true;
        } else {
            //if (LerValor.StringToFloat(jfmVRCH.getText()) + LerValor.StringToFloat(jfmVRDN.getText()) == 0)  {
                float result = (LerValor.StringToFloat(jTROCO.getText()) * -1) + LerValor.StringToFloat(jRESTO.getText()) + LerValor.StringToFloat(jfmVRDN.getText()) + LerValor.StringToFloat(jfmVRCH.getText());
                jRESTO.setValue(result);
                jTROCO.setValue(0);

                jbt = true;
                Enable(false);
                btEnabled(true);
                jbtCancelar.setEnabled(true);
                retorno = false;
            //}
        }
        return retorno;
    }

    public void Enable(boolean enb) {
        if (!enb) {
            jfmCT.setEnabled(enb);
            jfmCT.setText("");
            jfmBC.setEnabled(enb);
            jfmBC.setText("");
            jfmAG.setEnabled(enb);
            jfmAG.setText("");
            jfmCH.setEnabled(enb);
            jfmCH.setText("");
            jfmDT.setEnabled(enb);
            jfmDT.setDate(null);
            jfmVRCH.setEnabled(enb);
            jfmVRCH.setValue(0);
            jfmVRDN.setEnabled(enb);
            jfmVRDN.setValue(0);
        }
        jtgDN.setEnabled(enb);
        jtgCH.setEnabled(enb);
        jtgCT.setEnabled(enb);
        jbtLancar.setEnabled(enb);
        jbtCancelar.setEnabled(enb);
    }

    public void Clear() {
        jfmCT.setText("");
        jfmBC.setText("");
        jfmAG.setText("");
        jfmCH.setText("");
        jfmDT.setDate(null);
        jfmVRCH.setValue(0);
        jfmVRDN.setValue(0);
        jRESTO.setText("0,00");
        jTROCO.setText("0,00");
    }

    public void btEnabled(boolean enb) {
        jtgDN.setEnabled(enb);
        jtgCH.setEnabled(enb);
        jtgCT.setEnabled(enb);
        jbtLancar.setEnabled(!enb);
        jbtCancelar.setEnabled(!enb);
    }

    public void Escolha(int tipo) {
        if (tipo == 1) {
                jlbDN.setBackground(Color.red);
                jlbDN.setForeground(Color.yellow);

                jlbCH.setBackground(Color.white);
                jlbCH.setForeground(Color.black);

                jlbCT.setBackground(Color.white);
                jlbCT.setForeground(Color.black);

                jfmCT.setEnabled(false);
                jfmCT.setText("");
                jfmBC.setEnabled(false);
                jfmBC.setText("");
                jfmAG.setEnabled(false);
                jfmAG.setText("");
                jfmCH.setEnabled(false);
                jfmCH.setText("");
                jfmDT.setEnabled(false);
                jfmDT.setDate(null);
                jfmVRCH.setEnabled(false);
                jfmVRCH.setValue(0);

                jfmVRDN.setEnabled(true);
                jfmVRDN.setValue(0);
                jfmVRDN.requestFocus();

        } else if (tipo == 2) {
                jlbDN.setBackground(Color.white);
                jlbDN.setForeground(Color.black);

                jlbCH.setBackground(Color.red);
                jlbCH.setForeground(Color.yellow);

                jlbCT.setBackground(Color.white);
                jlbCT.setForeground(Color.black);

                jfmCT.setEnabled(false);
                jfmCT.setText("");
                jfmVRDN.setEnabled(false);
                jfmVRDN.setValue(0);

                jfmBC.setEnabled(true);
                jfmBC.setText("");
                jfmAG.setEnabled(true);
                jfmAG.setText("");
                jfmCH.setEnabled(true);
                jfmCH.setText("");
                jfmDT.setEnabled(true);
                jfmDT.setDate(null);
                jfmVRCH.setEnabled(true);
                jfmVRCH.setValue(0);
               jfmBC.requestFocus();

        } else if (tipo == 3) {
                jlbDN.setBackground(Color.white);
                jlbDN.setForeground(Color.black);

                jlbCH.setBackground(Color.white);
                jlbCH.setForeground(Color.black);

                jlbCT.setBackground(Color.red);
                jlbCT.setForeground(Color.yellow);

                jfmBC.setEnabled(false);
                jfmBC.setText("");
                jfmAG.setEnabled(false);
                jfmAG.setText("");
                jfmCH.setEnabled(false);
                jfmCH.setText("");
                jfmDT.setEnabled(false);
                jfmDT.setDate(null);
                jfmVRCH.setEnabled(false);
                jfmVRCH.setValue(0);

                jfmCT.setEnabled(true);
                jfmCT.setText("");
                jfmVRDN.setEnabled(true);
                jfmVRDN.setValue(0);
                jfmCT.requestFocus();
        } else {
                jlbDN.setBackground(Color.white);
                jlbDN.setForeground(Color.black);
                jtgDN.setSelected(false);

                jlbCH.setBackground(Color.white);
                jlbCH.setForeground(Color.black);
                jtgCH.setSelected(false);

                jlbCT.setBackground(Color.white);
                jlbCT.setForeground(Color.black);
                jtgCT.setSelected(false);

                jfmBC.setEnabled(false);
                jfmBC.setText("");
                jfmAG.setEnabled(false);
                jfmAG.setText("");
                jfmCH.setEnabled(false);
                jfmCH.setText("");
                jfmDT.setEnabled(false);
                jfmDT.setDate(null);
                jfmVRCH.setEnabled(false);
                jfmVRCH.setValue(0);

                jfmCT.setEnabled(false);
                jfmCT.setText("");
                jfmVRDN.setEnabled(false);
                jfmVRDN.setValue(0);
        }

        tpOPC = tipo;

        if (tipo < 4) {Enable(true); btEnabled(false); jbt = false;}
    }

    public String[][] Transicao(String acao) throws SQLException {
        String sql = "SELECT data, tipo, operacao, acao, cartao, datapre, banco, agencia, cheque, SUM(" +
                "StrVal(vrdinheiro)) vrdinheiro, SUM(" + 
                "StrVal(vrcheque)) vrcheque FROM transicao WHERE Lower(ncaixa) = '&1.' AND acao = '&2.' AND data = '&3.' GROUP BY banco, agencia, cheque, tipo, operacao, cartao, datapre;";
        sql = FuncoesGlobais.Subst(sql, new String[] {VariaveisGlobais.usuario.toLowerCase(), acao.toUpperCase(), Dates.DateFormata("dd/MM/yyyy", new Date())});
        ResultSet rs = conn.OpenTable(sql, null);
        String[][] retorno = {};

        while (rs.next()) {
            String stipo = rs.getString("tipo");
            String soper = rs.getString("operacao");
            String sacao = rs.getString("acao");
            String scartao = rs.getString("cartao");
            String sdtpre = rs.getString("datapre");
            String sbanco = rs.getString("banco");
            String sagencia = rs.getString("agencia");
            String scheque = rs.getString("cheque");

            String svrdinheiro = rs.getString("vrdinheiro");
            String svrcheque = rs.getString("vrcheque");

            retorno = FuncoesGlobais.ArraysAdd(retorno, new String[]
                    {sdtpre, sbanco,sagencia, scheque,
                    (rs.getFloat("vrdinheiro") > 0 ? svrdinheiro : svrcheque),
                    stipo, soper, sacao, scartao});
        }

        conn.CloseTable(rs);
        return retorno;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jGrupo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField jRESTO;
    private javax.swing.JFormattedTextField jTROCO;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtLancar;
    private javax.swing.JFormattedTextField jfmAG;
    private javax.swing.JFormattedTextField jfmBC;
    private javax.swing.JFormattedTextField jfmCH;
    private javax.swing.JFormattedTextField jfmCT;
    private com.toedter.calendar.JDateChooser jfmDT;
    private javax.swing.JFormattedTextField jfmVRCH;
    private javax.swing.JFormattedTextField jfmVRDN;
    private javax.swing.JLabel jlbCH;
    private javax.swing.JLabel jlbCT;
    private javax.swing.JLabel jlbDN;
    private javax.swing.JToggleButton jtgCH;
    private javax.swing.JToggleButton jtgCT;
    private javax.swing.JToggleButton jtgDN;
    // End of variables declaration//GEN-END:variables

}
