package Movimento.AdmParametros;

import Funcoes.Db;
import Funcoes.TableControl;
import Funcoes.VariaveisGlobais;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

public class jADMBancos extends javax.swing.JPanel {
    Db conn = VariaveisGlobais.conexao;
    boolean pixInclusao = false;

    /**
     * Creates new form jADMBancos
     */
    public jADMBancos() {
        initComponents();
        LerBancoPix();        
        pixConfig();        
        ListaContasBoletas();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jbancoDv = new javax.swing.JTextField();
        jcarteira = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        pixTag = new javax.swing.JLabel();
        pixTipo = new javax.swing.JComboBox<>();
        jLabel59 = new javax.swing.JLabel();
        pixBanco = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        pixTable = new javax.swing.JTable();
        pixIncluir = new javax.swing.JButton();
        pixExcluir = new javax.swing.JButton();
        pixChave = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jmoeda = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jAgencia = new javax.swing.JTextField();
        jtarifa = new javax.swing.JTextField();
        jConta = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jNossoNumero = new javax.swing.JTextField();
        jCtaDv = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblBcos = new javax.swing.JTable();
        jbcoDel = new javax.swing.JButton();
        jbcoAdc = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jbanco = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(772, 314));
        setMinimumSize(new java.awt.Dimension(772, 314));
        setPreferredSize(new java.awt.Dimension(772, 314));

        jLabel21.setText("Carteira:");

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("  .:: Chaves Pix");
        jLabel56.setOpaque(true);

        pixTag.setText("Tipo:");

        pixTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telefone", "EMail", "CPF", "CNPJ", "Outro" }));
        pixTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pixTipoActionPerformed(evt);
            }
        });

        jLabel59.setText("Banco:");

        pixBanco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pixBancoFocusLost(evt);
            }
        });

        pixTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Tipo", "Chave", "Banco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pixTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pixTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(pixTable);

        pixIncluir.setText("Incluir");
        pixIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pixIncluirActionPerformed(evt);
            }
        });

        pixExcluir.setText("Excluir");
        pixExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pixExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(pixTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pixTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pixChave, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pixBanco))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pixIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pixExcluir))))
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jLabel56)
                .addGap(12, 12, 12)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pixTag)
                    .addComponent(pixTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(pixBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pixChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(pixIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pixExcluir))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setText("Moeda:");

        jLabel18.setText("Agencia:");

        jLabel24.setText("Tarifa:");

        jtarifa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtarifa.setText("0,00");

        jLabel25.setText("Nosso Numero:");

        jLabel19.setText("Conta:");

        jNossoNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jNossoNumero.setText("0000000000000");

        jtblBcos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Agencia", "Conta", "DV", "N.Banco", "Carteira", "Moeda", "Tarifa", "N.Numero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblBcos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtblBcos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtblBcos);

        jbcoDel.setText("Excluir");
        jbcoDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcoDelActionPerformed(evt);
            }
        });

        jbcoAdc.setText("Incluir");
        jbcoAdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcoAdcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbcoAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbcoDel)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jbcoAdc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbcoDel))
        );

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Numero do Banco:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jConta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCtaDv, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbanco, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbancoDv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNossoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCtaDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbancoDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jcarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jmoeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jtarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jNossoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pixTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pixTipoActionPerformed
        int selecao = pixTipo.getSelectedIndex();
        pixChave.setValue(null);
        if (selecao == 0) {
            try { pixChave.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("+##(##)#####-####"))); } catch (ParseException ex) {}
        } else if (selecao == 1 || selecao > 3) {
            try { pixChave.setFormatterFactory(new DefaultFormatterFactory(null)); } catch (Exception ex) {}
        } else if (selecao == 2) {
            try { pixChave.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("###.###.###-##"))); } catch (ParseException ex) {}
        } else if (selecao == 3) {
            try { pixChave.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("##.###.###/####-##"))); } catch (ParseException ex) {}
        }
        pixChave.requestFocus();
    }//GEN-LAST:event_pixTipoActionPerformed

    private void pixBancoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pixBancoFocusLost
        if (pixInclusao) {
            // Gravar
            String insertSQL = "INSERT INTO `bancos_pix`(`tipo`,`chave`,`banco`) " +
            "VALUES ('" + pixTipo.getSelectedItem().toString() + "','" +
            pixChave.getText() + "','" + pixBanco.getText() + "');";
            conn.CommandExecute(insertSQL);

            pixTipo.setEnabled(false);
            pixChave.setEnabled(false);
            pixBanco.setEnabled(false);

            pixInclusao = false;
            LerBancoPix();
        }
    }//GEN-LAST:event_pixBancoFocusLost

    private void pixIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pixIncluirActionPerformed
        pixInclusao = true;
        pixTipo.setSelectedIndex(0);
        pixTipo.setEnabled(true);
        pixChave.setValue(null);
        pixChave.setEnabled(true);
        pixBanco.setText("");
        pixBanco.setEnabled(true);
        pixTag.setToolTipText(null);
        pixTipo.requestFocus();
    }//GEN-LAST:event_pixIncluirActionPerformed

    private void pixExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pixExcluirActionPerformed
        Object[] options = { "Sim", "Não" };
        int n = JOptionPane.showOptionDialog(null,
            "Deseja este conta PIX ? ",
            "Atenção", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (n == JOptionPane.NO_OPTION) return;

        int pos = pixTable.getSelectedRow();
        if (pos > -1) {
            String tid = pixTable.getModel().getValueAt(pos, 0).toString().trim();
            String sql = "DELETE FROM bancos_pix WHERE id = '" + tid + "';";
            try { conn.CommandExecute(sql); } catch (Exception e) {e.printStackTrace();}
        }
        LerBancoPix();
    }//GEN-LAST:event_pixExcluirActionPerformed

    private void jbcoAdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcoAdcActionPerformed
        bcoAdc();
    }//GEN-LAST:event_jbcoAdcActionPerformed

    private void jbcoDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcoDelActionPerformed
        bcoDel();
    }//GEN-LAST:event_jbcoDelActionPerformed

    private void pixConfig() {
        pixInclusao = false;
        pixTipo.setSelectedIndex(0);
        pixTipo.setEnabled(false);
        pixChave.setValue(null);
        pixChave.setEnabled(false);
        pixBanco.setText("");
        pixBanco.setEnabled(false);
        pixTipo.requestFocus();
    }
    
    private void ListaContasBoletas() {
        String sql = "SELECT id, agencia, conta, conta_dv, nbanco, nbancodv, carteira, moeda, tarifa, nnumero FROM contas_boletas ORDER BY id;";

        TableControl.Clear(jtblBcos);
        // Seta Cabecario
        TableControl.header(jtblBcos, new String[][] {
            {"id", "Agencia", "Conta", "DV", "N.Banco", "DV", "Carteira", "moeda", "tarifa", "N.Numero"},
            {"15","80","100","30","80","20","80","60","80","100"}
        });

        ResultSet rs = conn.OpenTable(sql, null);
        try {
            while (rs.next()) {
                String pid = rs.getString("id");
                String pagencia = rs.getString("agencia");
                String pconta =  rs.getString("conta");
                String pcontadv =  rs.getString("conta_dv");
                String pnbanco =  rs.getString("nbanco");
                String pnbancodv = rs.getString("nbancodv");
                String pcarteira =  rs.getString("carteira");
                String pmoeda =  rs.getString("moeda");
                String ptarifa =  rs.getString("tarifa");
                String pnnumero =  rs.getString("nnumero");
                TableControl.add(jtblBcos, new String[][]{
                    {pid, pagencia, pconta, pcontadv, pnbanco, pnbancodv, pcarteira, pmoeda, ptarifa, pnnumero},
                    {"C","L","L","C","L","L","C","R","R"}
                }, true);
            }
        } catch (SQLException ex) {ex.printStackTrace();}
        conn.CloseTable(rs);
    }
    
    private void bcoAdc() {
        String tagencia = jAgencia.getText();
        String tconta = jConta.getText();
        String tcontadv = jCtaDv.getText();
        String tnbanco = jbanco.getText();
        String tnbancodv = jbancoDv.getText();
        String tcarteira = jcarteira.getText();
        String tmoeda = jmoeda.getText();
        String ttarifa = jtarifa.getText();
        String tnnumero = jNossoNumero.getText();
        
        String sql = "INSERT INTO contas_boletas (agencia, conta, conta_dv, nbanco, nbancodv, carteira, moeda, tarifa, nnumero) VALUES ('" + tagencia + "','" +
                tconta + "','" + tcontadv + "','" + tnbanco + "','" + tnbancodv + "','" +
                tcarteira + "','" + tmoeda + "','" + ttarifa + "','" + tnnumero + "');";
        try {
            conn.CommandExecute(sql);
        } catch (Exception e) {e.printStackTrace();}
        
        jAgencia.setText("");
        jConta.setText("");
        jCtaDv.setText("");
        jbanco.setText("");
        jbancoDv.setText("");
        jcarteira.setText("");
        jmoeda.setText("");
        jtarifa.setText("");
        jNossoNumero.setText("");
        
        ListaContasBoletas();
    }
    
    private void bcoDel() {
        int pos = jtblBcos.getSelectedRow();
        if (pos > -1) {
            String tid = jtblBcos.getModel().getValueAt(pos, 0).toString().trim();
            String sql = "DELETE FROM contas_boletas WHERE id = '" + tid + "';";
            try { conn.CommandExecute(sql); } catch (Exception e) {e.printStackTrace();}
        }
        ListaContasBoletas();
    }
    
    private void LerBancoPix() {
        conn.BancoPix();
        
        String sql = "SELECT id, tipo, chave, banco FROM bancos_pix ORDER BY id;";

        TableControl.Clear(pixTable);
        // Seta Cabecario
        TableControl.header(pixTable, new String[][] {
            {"id", "Tipo", "Chave", "Banco"},
            {"0","80","100","80"}
        });

        ResultSet rs = conn.OpenTable(sql, null);
        try {
            while (rs.next()) {
                int pid = rs.getInt("id");
                String ptipo = rs.getString("tipo");
                String pchave =  rs.getString("chave");
                String pbanco =  rs.getString("banco");
                TableControl.add(pixTable, new Object[][]{
                    {pid, ptipo, pchave, pbanco},{"C","C","L","L"}
                }, true);
            }
        } catch (SQLException ex) {ex.printStackTrace();}
        conn.CloseTable(rs);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAgencia;
    private javax.swing.JTextField jConta;
    private javax.swing.JTextField jCtaDv;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JTextField jNossoNumero;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jbanco;
    private javax.swing.JTextField jbancoDv;
    private javax.swing.JButton jbcoAdc;
    private javax.swing.JButton jbcoDel;
    private javax.swing.JTextField jcarteira;
    private javax.swing.JTextField jmoeda;
    private javax.swing.JTextField jtarifa;
    private javax.swing.JTable jtblBcos;
    private javax.swing.JTextField pixBanco;
    private javax.swing.JFormattedTextField pixChave;
    private javax.swing.JButton pixExcluir;
    private javax.swing.JButton pixIncluir;
    private javax.swing.JTable pixTable;
    private javax.swing.JLabel pixTag;
    private javax.swing.JComboBox<String> pixTipo;
    // End of variables declaration//GEN-END:variables
}
