package Movimento.AdmParametros;

import Funcoes.VariaveisGlobais;
import static Funcoes.gmail.GmailAPI.AuthGmail;
import static Funcoes.gmail.GmailAPI.LoadGmailJSon;
import static Funcoes.gmail.GmailAPI.ReadJSon;
import static Funcoes.gmail.GmailAPI.openWebpage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.GeneralSecurityException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONException;

public class jADMEmail extends javax.swing.JPanel {

    /**
     * Creates new form jADMEmail
     */
    public jADMEmail() {
        initComponents();
        
        // Liga Abas de configuração de email caso não esteja configurado
        File filePath = new File(System.getProperty("user.dir") + "/cert/" + VariaveisGlobais.dCliente.get("marca").trim() + "_credentials.json");
        {
            // Aba GMail
            //jTabbedGmail.setEnabled(!filePath.exists());
            //jPanelGmail.setEnabled(!filePath.exists());
            BtnGoogleConsole.setEnabled(!filePath.exists());
            gCredentialsFile.setEnabled(!filePath.exists());
            BtnGenerateCode.setEnabled(!filePath.exists());
            gAuthCode.setEnabled(!filePath.exists());
            BtnGenerateCredentialsFile.setEnabled(!filePath.exists());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        BtnGenerateCode = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        gAuthCode = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        BtnGenerateCredentialsFile = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        BtnGoogleConsole = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        gCredentialsFile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(772, 314));
        setMinimumSize(new java.awt.Dimension(772, 314));

        jLabel27.setText("File:");

        BtnGenerateCode.setText("Gerar");
        BtnGenerateCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerateCodeActionPerformed(evt);
            }
        });

        jLabel28.setText("* - 3º Copie e Cole o Code da página para aqui.");

        jLabel29.setText("Code:");

        jLabel30.setText("* - 4º Gere aqui seu arquivo credentials.json.");

        BtnGenerateCredentialsFile.setText("Gerar");
        BtnGenerateCredentialsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerateCredentialsFileActionPerformed(evt);
            }
        });

        jLabel31.setText("* - 1º Crie o Projeto e baixe o arquivo .json");

        BtnGoogleConsole.setText("Google Console");
        BtnGoogleConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGoogleConsoleActionPerformed(evt);
            }
        });

        jLabel32.setText("* - 2º Selecio o arquivo .json baixado para poder Autorizar e Criar o Code.");

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Configurações para envio via conta do GMail");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)
                                    .addComponent(BtnGoogleConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnGenerateCredentialsFile))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(gAuthCode, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(gCredentialsFile, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnGenerateCode)
                            .addGap(2, 2, 2)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(BtnGoogleConsole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gCredentialsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(BtnGenerateCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gAuthCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(BtnGenerateCredentialsFile))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGenerateCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerateCodeActionPerformed
        try {
            AuthGmail(gCredentialsFile.getText());
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BtnGenerateCodeActionPerformed

    private void BtnGenerateCredentialsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerateCredentialsFileActionPerformed
        try {
            LoadGmailJSon(gCredentialsFile.getText(), gAuthCode.getText());
        } catch (IOException | GeneralSecurityException ex) {
            Logger.getLogger(jADMParametros.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ReadJSon();
        } catch (JSONException ex) {
            Logger.getLogger(jADMParametros.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Credenciais criadas com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        // Liga Abas de configuração de email caso não esteja configurado
        File filePath = new File(System.getProperty("user.dir") + "/cert/" + VariaveisGlobais.dCliente.get("marca").trim() + "_credentials.json");
            {
                // Aba GMail
                //jTabbedGmail.setEnabled(!filePath.exists());
                //jPanelGmail.setEnabled(!filePath.exists());
                BtnGoogleConsole.setEnabled(!filePath.exists());
                gCredentialsFile.setEnabled(!filePath.exists());
                BtnGenerateCode.setEnabled(!filePath.exists());
                gAuthCode.setEnabled(!filePath.exists());
                BtnGenerateCredentialsFile.setEnabled(!filePath.exists());
            }
            if (!filePath.exists()) VariaveisGlobais.OUTLOOK = true;
    }//GEN-LAST:event_BtnGenerateCredentialsFileActionPerformed

    private void BtnGoogleConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGoogleConsoleActionPerformed
        try {
            // Abrir página no navegador padrão: https://console.developers.google.com/
            openWebpage(new URL("https://console.developers.google.com/"));
        } catch (MalformedURLException ex) {
            Logger.getLogger(jADMParametros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGoogleConsoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGenerateCode;
    private javax.swing.JButton BtnGenerateCredentialsFile;
    private javax.swing.JButton BtnGoogleConsole;
    private javax.swing.JTextField gAuthCode;
    private javax.swing.JTextField gCredentialsFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    // End of variables declaration//GEN-END:variables
}
