package Sici.Locatarios;

import Funcoes.CEPEndereco;
import Funcoes.ClienteViaCepWS;
import Funcoes.Db;
import Funcoes.Estados;
import Funcoes.TableControl;
import Funcoes.VariaveisGlobais;
import Funcoes.newTable;
import java.util.List;
import java.nio.charset.StandardCharsets;

/**
 *
 * @author supervisor
 */
public class BuscaCep extends javax.swing.JDialog {
    int tam = 0, n = 0;
    Db conn = VariaveisGlobais.conexao;
    public Object[] dados = null;
    
    /**
     * Creates new form BuscaCep
     */
    public BuscaCep(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        String[] aheaders = {"Logradouro","Nomeslog","Endereço","Bairro","Cidade","Uf","Cep"};
        int[] widths = {0,250,500,250,250,100,150};
        String[] aligns = {"L","L","L","L","L","L","L"};
        newTable.InitTable(tblCEPS, aheaders, widths, aligns, true);
        
        setLocationRelativeTo(null);
        
        for (Estados i : Funcoes.FuncoesGlobais.listaEstado()) {
            cEstado.addItem(i.getSigla());
        }
        cCidade.setText("");
    }

    private void SeekCep(String cestado, String ccidade, String cendereco) {
        TableControl.Clear(tblCEPS);
        
        List<CEPEndereco> ceps = ClienteViaCepWS.buscaEnderecos(cestado, ccidade, cendereco);
        if (ceps.size() > 0) {
            try {
                tam = ceps.size();
                n = 1;
                jbarra.setValue(0);
                jbarra.setVisible(true);

                for (CEPEndereco item : ceps) {
                    new Thread() {
                        public void run() {
                            int pos = (n * 100) / tam;
                            try {sleep(100);} catch (Exception ex) {}
                            jbarra.setValue(pos);
                            jbarra.repaint();
                        }
                    }.start();                

                    String slogra = NormalizeText(item.getComplemento());
                    String sender = NormalizeText(item.getComplemento());
                    String sendbc = NormalizeText(item.getLogradouro());
                    String sbairr = NormalizeText(item.getBairro());
                    String scidad = NormalizeText(item.getLocalidade());
                    String suf    = NormalizeText(item.getUf());
                    String scep   = NormalizeText(item.getCep());

                    Object[] linha = {slogra, sender, sendbc, sbairr, scidad, suf, scep};
                    newTable.add(tblCEPS, linha);

                    this.n++;
                }
            } catch (Exception err) {}
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCEPS = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cEnd = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        jbarra = new javax.swing.JProgressBar();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:: Busca de Cep por endereço...");
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);

        tblCEPS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCEPS.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCEPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCEPSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCEPS);

        jLabel3.setText("Estado:");

        jLabel4.setText("Cidade:");

        jLabel1.setText("End.:");

        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/find.png"))); // NOI18N
        jbtBuscar.setMnemonic('B');
        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscar)
                    .addComponent(jLabel3)
                    .addComponent(cEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        new Thread() {public void run() {SeekCep(cEstado.getSelectedItem().toString(), cCidade.getText(), cEnd.getText());}}.start();
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void tblCEPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCEPSMouseClicked
        int row = tblCEPS.getSelectedRow(); 
        if (row < 0) {
            dados = null;
        } else {
            if (evt.getClickCount() == 2) {
                String sender = tblCEPS.getModel().getValueAt(row, 1).toString();
                String slogra = tblCEPS.getModel().getValueAt(row, 2).toString();
                String sbairr = tblCEPS.getModel().getValueAt(row, 3).toString();
                String scidad = tblCEPS.getModel().getValueAt(row, 4).toString();
                String sestad = tblCEPS.getModel().getValueAt(row, 5).toString();
                String scep   = tblCEPS.getModel().getValueAt(row, 6).toString();
                dados = new Object[] {slogra, sender, sbairr, scidad, sestad, scep};
                
                this.dispose();
            }
        }
    }//GEN-LAST:event_tblCEPSMouseClicked

    private String NormalizeText(String texto) {
        return new String(texto.getBytes(StandardCharsets.ISO_8859_1), StandardCharsets.UTF_8);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscaCep dialog = new BuscaCep(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cCidade;
    private javax.swing.JTextField cEnd;
    private javax.swing.JComboBox<String> cEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar jbarra;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JTable tblCEPS;
    // End of variables declaration//GEN-END:variables
}
