package Sici.Locatarios;

import Funcoes.FuncoesGlobais;
import Funcoes.LimitedTextField;
import Funcoes.VariaveisGlobais;
import java.awt.AWTKeyStroke;
import java.awt.Dimension;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import javax.swing.JOptionPane;

public class jFichaSocios extends javax.swing.JDialog {
    boolean bNew = false;

    /** Creates new form jFichaSocios */
    public jFichaSocios(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();

        //Centraliza a janela.
        Dimension dimension = this.getToolkit().getScreenSize();
        int x = (int) (dimension.getWidth() - this.getSize().getWidth() ) / 2;
        int y = (int) (dimension.getHeight() - this.getSize().getHeight()) / 2;
        this.setLocation(x,y);

        // Colocando enter para pular de campo
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);

        btIncluir.setEnabled(!(VariaveisGlobais.mQtdSoc > 3));
        if (VariaveisGlobais.mContrato != "") LerDados();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sNome = new LimitedTextField(60);
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sDtNasc = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel14 = new javax.swing.JLabel();
        sNacionalidade = new LimitedTextField(25);
        jLabel15 = new javax.swing.JLabel();
        sEstCivil = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        sCpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        sIdentidade = new LimitedTextField(20);
        jLabel10 = new javax.swing.JLabel();
        sMae = new LimitedTextField(60);
        jLabel11 = new javax.swing.JLabel();
        sPai = new LimitedTextField(60);
        jLabel2 = new javax.swing.JLabel();
        sCargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sRetirada = new javax.swing.JFormattedTextField();
        btRetornar = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel7.setText("Nome:");
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 25));

        jLabel8.setText("Dt.Nasc:");

        sDtNasc.setDate(new java.util.Date(-2208977612000L));

        jLabel14.setText("Nac.:");

        sNacionalidade.setName("sNacionalidade"); // NOI18N

        jLabel15.setText("Est. Civil:");

        sEstCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteriro(a)", "Casado(a)", "Separado(a)", "Divorciado(a)", "Viuvo(a)" }));
        sEstCivil.setName("sEstCivil"); // NOI18N

        jLabel1.setText("Cpf:");

        try {
            sCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        sCpf.setText("");
        sCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sCpfFocusLost(evt);
            }
        });

        jLabel6.setText("RG:");

        jLabel10.setText("Mãe:");

        jLabel11.setText("Pai:");

        jLabel2.setText("Cargo:");

        jLabel3.setText("Renda:");

        sRetirada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        sRetirada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btRetornar.setText("Retornar");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sMae, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sPai))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sNome, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sCpf)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel14, jLabel6, jLabel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sNacionalidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(sEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sIdentidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sRetirada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sDtNasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sMae, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(sPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel14, jLabel15, jLabel2, jLabel3, jLabel6, jLabel7, jLabel8});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        bNew = true;
        btIncluir.setEnabled(false);
        btGravar.setEnabled(true);
        btRetornar.setEnabled(true);

        LimparDados();
        sNome.requestFocus();
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        if (sNome.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo 'NOME' nào pode ser vazio!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            sNome.requestFocus();
            return;
        }

        if (sCpf.getText().replace(".", "").replace("-", "").trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo 'CPF' nào pode ser vazio!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            sCpf.requestFocus();
            return;
        }

        try {
            GravarDados();
        } catch (SQLException ex) { ex.printStackTrace();}

        bNew = false;

        // Bloqueio dos botões
        btIncluir.setEnabled(!(VariaveisGlobais.mQtdSoc > 3));
        btGravar.setEnabled(true);
        btRetornar.setEnabled(true);

    }//GEN-LAST:event_btGravarActionPerformed

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
        if (bNew) {
            try {
                LerDados();

                // Bloqueio dos botões
                btIncluir.setEnabled(!(VariaveisGlobais.mQtdSoc > 3));
                btGravar.setEnabled(true);
                btRetornar.setEnabled(true);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            bNew = false;
        } else this.dispose();
    }//GEN-LAST:event_btRetornarActionPerformed

    private void sCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sCpfFocusLost
        if (!FuncoesGlobais.ValidarCPFCNPJ(sCpf.getText())) sCpf.requestFocus();
    }//GEN-LAST:event_sCpfFocusLost

    private void GravarDados() throws SQLException {
        SimpleDateFormat fm = new SimpleDateFormat("yyyy/MM/dd");

        if (bNew) {
            VariaveisGlobais.mQtdSoc += 1;
        }

        String tDtNasc = "0000-00-00";
        try {
            tDtNasc = fm.format(sDtNasc.getDate()).toString();
        } catch (Exception ex) { ex.printStackTrace(); }
        
        String sqlUpdate = "UPDATE locatarios SET " + 
                           "socionome" + VariaveisGlobais.mQtdSoc + " = '%s', " +
                           "sociodtnasc" + VariaveisGlobais.mQtdSoc + " = '%s', " +
                           "socionac" + VariaveisGlobais.mQtdSoc + "= '%s', " +
                           "socioecivil" + VariaveisGlobais.mQtdSoc + "= '%s', " +
                           "sociocpf" + VariaveisGlobais.mQtdSoc + "= '%s', " +
                           "sociorg" + VariaveisGlobais.mQtdSoc + "= '%s', " +
                           "sociosalario" + VariaveisGlobais.mQtdSoc + "= '%s', " +
                           "sociocargo" + VariaveisGlobais.mQtdSoc + "= '%s', " +
                           "sociomae" + VariaveisGlobais.mQtdSoc + "= '%s', " +
                           "sociopai" + VariaveisGlobais.mQtdSoc + "= '%s' WHERE contrato = '%s';";
        sqlUpdate = String.format(sqlUpdate, sNome.getText(), tDtNasc, sNacionalidade.getText(), 
                sEstCivil.getSelectedItem().toString(),
                sCpf.getText(), sIdentidade.getText(), sRetirada.getText(), sCargo.getText(),
                sMae.getText(), sPai.getText(), VariaveisGlobais.pResult.getString("contrato"));
        VariaveisGlobais.conexao.CommandExecute(sqlUpdate);
    }

    private void LimparDados() {
        sNome.setText("");
        sDtNasc.setDate(null);
        sNacionalidade.setText("");
        sEstCivil.setSelectedIndex(0);
        sCpf.setText("");
        sIdentidade.setText("");
        sMae.setText("");
        sPai.setText("");
        sCargo.setText("");
        sRetirada.setText("");
    }

    private void LerDados() throws SQLException {
        sNome.setText(VariaveisGlobais.pResult.getString("socionome" + VariaveisGlobais.mPosSoc));
        Date tDtNascConj = null;
        try {
            tDtNascConj = VariaveisGlobais.pResult.getDate("sociodtnasc" + VariaveisGlobais.mPosSoc);
        } catch (SQLException ex) { ex.printStackTrace(); }
        sDtNasc.setDate(tDtNascConj);

        sNacionalidade.setText(VariaveisGlobais.pResult.getString("socionac" + VariaveisGlobais.mPosSoc));

        String pCivil = VariaveisGlobais.pResult.getString("socioecivil" + VariaveisGlobais.mPosSoc).trim().toLowerCase();
        String sCivil[] = {"solteiro","solteira","casado","casada","separado","separada","divorciado","divorciada","viuvo","viuva"};
        Integer nPos = FuncoesGlobais.IndexOf(sCivil,pCivil) ;
        if (nPos == -1) {
            nPos = 0;
        }
        else if (nPos == 0 || nPos == 1){
            nPos = 0;
        }
        else if (nPos == 2 || nPos == 3) {
            nPos = 1;
        }
        else if (nPos == 4 || nPos == 5) {
            nPos = 2;
        }
        else if (nPos == 6 || nPos == 7) {
            nPos = 3;
        }
        else if (nPos == 8 || nPos == 9 ) {
            nPos = 4;
        }
        else
            nPos = 0;

        sEstCivil.setSelectedIndex(nPos);


        sCpf.setText(VariaveisGlobais.pResult.getString("sociocpf" + VariaveisGlobais.mPosSoc));
        sIdentidade.setText(VariaveisGlobais.pResult.getString("sociorg" + VariaveisGlobais.mPosSoc));
        sMae.setText(VariaveisGlobais.pResult.getString("sociomae" + VariaveisGlobais.mPosSoc));
        sPai.setText(VariaveisGlobais.pResult.getString("sociopai" + VariaveisGlobais.mPosSoc));
        sCargo.setText(VariaveisGlobais.pResult.getString("sociocargo" + VariaveisGlobais.mPosSoc));
        sRetirada.setText(VariaveisGlobais.pResult.getString("sociosalario" + VariaveisGlobais.mPosSoc));
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jFichaSocios dialog = null;
                try {
                    dialog = new jFichaSocios(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField sCargo;
    private javax.swing.JFormattedTextField sCpf;
    private com.toedter.calendar.JDateChooser sDtNasc;
    private javax.swing.JComboBox sEstCivil;
    private javax.swing.JTextField sIdentidade;
    private javax.swing.JTextField sMae;
    private javax.swing.JTextField sNacionalidade;
    private javax.swing.JTextField sNome;
    private javax.swing.JTextField sPai;
    private javax.swing.JFormattedTextField sRetirada;
    // End of variables declaration//GEN-END:variables

}
