package RedeBancaria;

import Funcoes.Db;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ConfigBancos extends javax.swing.JInternalFrame {
    Db db = new Db(null);
    
    public ConfigBancos() {
        initComponents();

    }

    private void JTableBancos() {
        List<bancos> bancosList = new ArrayList();
        String selectSQL = "SELECT `id`, `banco`, `bancodv`, `agencia`, agenciadv`, " +
                           "`conta´, `contadv`, `carteira`, `beneficiario`, `path`, " +
                           "`ctrfile`, `keyfile`, `pfxfile`, clientid`, `clientsecret` " +
                           "FROM bancos_digital ORDER BY `id`;";
        ResultSet rs = db.OpenTable(selectSQL, null);
        try {
            while (rs.next()) {
                bancosList.add(new bancos(
                        rs.getInt("id"),
                        rs.getString("banco"),
                        rs.getString("bancodv"),
                        rs.getString("agencia"),
                        rs.getString("agenciadv"),
                        rs.getString("conta"),
                        rs.getString("contadv"),
                        rs.getString("carteira"),
                        rs.getString("beneficiario"),
                        rs.getString("path"),
                        rs.getString("crtfile"),
                        rs.getString("keyfile"),
                        rs.getString("pfxfile"),
                        rs.getString("clientid"),
                        rs.getString("clientsecret")
                ));
            }
        } catch (SQLException ex) {}
        db.CloseTable(rs);
        
        DefaultTableModel tableModel = new DefaultTableModel() {
            @Override
            public int getColumnCount() {
                return 16; 
            }

            @Override
            public String getColumnName(int column) {
                
                switch (column) {
                    case 0: return "ID";
                    case 1: return "Banco";
                    case 2: return "BancoDv";
                    case 3: return "Agencia";
                    case 4: return "AgenciaDv";
                    case 5: return "Conta";
                    case 6: return "ContaDv";
                    case 7: return "Carteira";
                    case 8: return "Beneficiario";
                    case 9: return "Path";
                    case 10: return "Crt File";
                    case 11: return "Key File";
                    case 12: return "Pfx File";
                    case 13: return "ClienteId";
                    case 14: return "ClientSecret";
                    
                    default: return "Coluna " + column;
                }
            }

            @Override
            public int getRowCount() {
                return bancosList.size();
            }

            @Override
            public Object getValueAt(int row, int column) {
                bancos banco = bancosList.get(row);
                switch (column) {
                    case 0: return banco.getId();
                    case 1: return banco.getBanco();
                    case 2: return banco.getBancodv();
                    case 3: return banco.getAgencia();
                    case 4: return banco.getAgenciadv();
                    case 5: return banco.getConta();
                    case 6: return banco.getContadv();
                    case 7: return banco.getCarteira();
                    case 8: return banco.getBeneficiario();
                    case 9: return banco.getPath();
                    case 10: return banco.getCrtfile();
                    case 11: return banco.getKeyfile();
                    case 12: return banco.getPfxfile();
                    case 13: return banco.getClientid();
                    case 14: return banco.getClientsecret();
                                        
                    default: return null;
                }
            }
        };        
        bd_Bancos.setModel(tableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bd_Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bd_Banco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bd_Agencia = new javax.swing.JTextField();
        bd_AgenciaDV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bd_Conta = new javax.swing.JTextField();
        bd_ContaDV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bd_Carteira = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bd_Beneficiario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bd_Path = new javax.swing.JTextField();
        bd_btPath = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bd_CrtFile = new javax.swing.JTextField();
        bd_btCrtFile = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bd_KeyFile = new javax.swing.JTextField();
        bd_btKeyFile = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        bd_Pfx = new javax.swing.JTextField();
        bd_btPfxFile = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bd_ClientId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bd_ClientSecret = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bd_Bancos = new javax.swing.JTable();
        btIncluir = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        bd_Buscar = new javax.swing.JTextField();
        bd_BancoDV = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Cadastro de Bancos Digitais");
        setMaximumSize(new java.awt.Dimension(784, 442));
        setMinimumSize(new java.awt.Dimension(784, 442));
        setVisible(true);

        jLabel1.setText("Id:");

        bd_Id.setEditable(false);
        bd_Id.setBackground(new java.awt.Color(255, 255, 255));
        bd_Id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Banco:");

        bd_Banco.setToolTipText("");

        jLabel3.setText("Agência:");

        jLabel4.setText("Conta:");

        jLabel5.setText("Carteira:");

        bd_Carteira.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Beneficiário:");

        jLabel7.setText("Path:");

        bd_Path.setEditable(false);
        bd_Path.setBackground(new java.awt.Color(255, 255, 255));

        bd_btPath.setText("...");

        jLabel8.setText("CRT:");

        bd_CrtFile.setEditable(false);
        bd_CrtFile.setBackground(new java.awt.Color(255, 255, 255));

        bd_btCrtFile.setText("...");

        jLabel9.setText("KEY:");

        bd_KeyFile.setEditable(false);
        bd_KeyFile.setBackground(new java.awt.Color(255, 255, 255));

        bd_btKeyFile.setText("...");

        jLabel10.setText("PFX:");

        bd_Pfx.setEditable(false);
        bd_Pfx.setBackground(new java.awt.Color(255, 255, 255));

        bd_btPfxFile.setText("...");

        jLabel11.setText("ClientId:");

        jLabel12.setText("Secret::");

        bd_Bancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(bd_Bancos);

        btIncluir.setText("Incluir");

        btExcluir.setText("Excluir");

        btAlterar.setText("Alterar");

        btGravar.setText("Gravar");

        btCancelar.setText("Cancelar");

        jLabel13.setText("Buscar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_Banco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_BancoDV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_Agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_AgenciaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_Conta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_ContaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_Carteira, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_Beneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_Path, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_btPath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_CrtFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_btCrtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_KeyFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_btKeyFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_Pfx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_btPfxFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_ClientId))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_ClientSecret))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bd_Buscar))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btIncluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bd_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(bd_Banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(bd_Agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bd_AgenciaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(bd_Conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bd_ContaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(bd_Carteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(bd_Beneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bd_BancoDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bd_Path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bd_btPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bd_CrtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bd_btCrtFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bd_KeyFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bd_btKeyFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(bd_Pfx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bd_btPfxFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bd_ClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bd_ClientSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(bd_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bd_Agencia;
    private javax.swing.JTextField bd_AgenciaDV;
    private javax.swing.JTextField bd_Banco;
    private javax.swing.JTextField bd_BancoDV;
    private javax.swing.JTable bd_Bancos;
    private javax.swing.JTextField bd_Beneficiario;
    private javax.swing.JTextField bd_Buscar;
    private javax.swing.JTextField bd_Carteira;
    private javax.swing.JTextField bd_ClientId;
    private javax.swing.JTextField bd_ClientSecret;
    private javax.swing.JTextField bd_Conta;
    private javax.swing.JTextField bd_ContaDV;
    private javax.swing.JTextField bd_CrtFile;
    private javax.swing.JTextField bd_Id;
    private javax.swing.JTextField bd_KeyFile;
    private javax.swing.JTextField bd_Path;
    private javax.swing.JTextField bd_Pfx;
    private javax.swing.JButton bd_btCrtFile;
    private javax.swing.JButton bd_btKeyFile;
    private javax.swing.JButton bd_btPath;
    private javax.swing.JButton bd_btPfxFile;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btIncluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
