package Movimento;

import Funcoes.Dates;
import Funcoes.Db;
import Funcoes.LerValor;
import Funcoes.VariaveisGlobais;
import Funcoes.jTableControl;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.sql.ResultSet;
import java.sql.SQLException;

public class jControleCheques extends javax.swing.JInternalFrame {
    jTableControl tabela = new jTableControl(true);
    jTableControl tabela2 = new jTableControl(true);
    static Db conn = VariaveisGlobais.conexao;

    /** Creates new form jControleCheques */
    public jControleCheques() {
        initComponents();

        // Icone da tela
        FlatSVGIcon icone = new FlatSVGIcon("menuIcons/deposito.svg",16,16);
        setFrameIcon(icone);        
        
        try {FillCheques();} catch (SQLException ex) {ex.printStackTrace();}
    }

    private void FillCheques() throws SQLException {
        String sql = "SELECT ch_data, ch_data2, ch_banco, ch_agencia, ch_ncheque, SUM(ch_valor) AS ch_valor, lower(ch_ncaixa) as nomecaixa " +
                 "FROM Cheques " +
                 "GROUP BY ch_data, ch_banco, ch_agencia, ch_ncheque, ch_ncaixa " +
                 "ORDER BY CH_DATA2,CH_DATA,CH_NCHEQUE;";
        //sql = FuncoesGlobais.Subst(sql, new String[] {VariaveisGlobais.usuario.toLowerCase().trim()});

        ResultSet rs = conn.OpenTable(sql, null);
        Integer[] tam = {100,100,50,80,90,90,50,70};
        String[] col = {"Dt.Lanc","Dt.Dep","Banco","Agencia","Cheque N°","Valor","Tipo", "caixa"};
        Boolean[] edt = {false,false,false,false,false,false,false,false};
        String[] aln = {"C","C","C","C","C","R","C","L"};
        Object[][] data = {};
        while (rs.next()) {
            String dDtLanc = Dates.DateFormata("dd/MM/yyyy", rs.getDate("ch_data"));
            
            String dDtDep = null;
            String dTipo = null;
            try {
                if (rs.getString("ch_data2") != "0000-00-00") {
                    if (rs.getString("ch_data2") != null) { dDtDep = Dates.DateFormata("dd/MM/yyyy", rs.getDate("ch_data2")); dTipo = "CP";}
                    else { dDtDep = Dates.DateFormata("dd/MM/yyyy", rs.getDate("ch_data")); dTipo = "CH";}
                }
            } catch (SQLException ex) {dDtDep = Dates.DateFormata("dd/MM/yyyy", rs.getDate("ch_data")); dTipo = "CH";}
            
            String dBanco = rs.getString("ch_banco");
            String dAgencia = rs.getString("ch_agencia");
            String dCheque = rs.getString("ch_ncheque");
            String dValor = LerValor.floatToCurrency(rs.getFloat("ch_valor"),2);
            String dnomecx = rs.getString("nomecaixa");
            
            Object[] dado = {dDtLanc, dDtDep, dBanco, dAgencia, dCheque, dValor, dTipo, dnomecx};
            data = tabela.insert(data, dado);
        }
        conn.CloseTable(rs);
        tabela.Show(jDep, data, tam, aln, col, edt);
    }
    
    private void FillChequesDep(String dtini, String dtfim) throws SQLException {
        String sql = "SELECT dtrecebimento, StrVal(Mid(campo,6,10)) AS ValorDep, rc_aut FROM auxiliar " +
                     "WHERE conta = 'DEP' and (dtrecebimento >= '" +
                     dtini + "' AND dtrecebimento <= '" + dtfim + "')";

        ResultSet rs = conn.OpenTable(sql, null);
        Integer[] tam = {100,100,50};
        String[] col = {"Dt.Dep","Valor","No.Aut."};
        Boolean[] edt = {false,false,false};
        String[] aln = {"C","R","C"};
        Object[][] data = {};
        while (rs.next()) {
            String dDtLanc = Dates.DateFormata("dd/MM/yyyy", rs.getDate("dtrecebimento"));
            String dValor = LerValor.floatToCurrency(rs.getFloat("ValorDep"),2);
            String dCheque = rs.getString("rc_aut");
            
            Object[] dado = {dDtLanc, dValor, dCheque};
            data = tabela2.insert(data, dado);
        }
        conn.CloseTable(rs);
        tabela2.Show(jADep, data, tam, aln, col, edt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDep = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDtInic = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel2 = new javax.swing.JLabel();
        jDtFim = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jbtListar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jADep = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Controle de Cheques ::.");
        setMaximumSize(new java.awt.Dimension(514, 299));
        setMinimumSize(new java.awt.Dimension(514, 299));
        setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "[ CHEQUES A DEPOSITAR ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDep.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jDep);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "[ CHEQUES DEPOSITADOS ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setText("Período:");

        jLabel2.setText("até");

        jbtListar.setText("Listar");
        jbtListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListarActionPerformed(evt);
            }
        });

        jADep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jADep);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDtInic, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtListar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtListar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDtFim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDtInic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListarActionPerformed
        String dini = Dates.DateFormata("yyyy-MM-dd", jDtInic.getDate());
        String dfim = Dates.DateFormata("yyyy-MM-dd", jDtFim.getDate());

        try { FillChequesDep(dini, dfim); } catch (Exception e) {}
    }//GEN-LAST:event_jbtListarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jADep;
    private javax.swing.JTable jDep;
    private com.toedter.calendar.JDateChooser jDtFim;
    private com.toedter.calendar.JDateChooser jDtInic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtListar;
    // End of variables declaration//GEN-END:variables
}
