package Movimento;

import Funcoes.*;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.lowagie.text.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.export.JRPdfExporter;

public class jContasControle extends javax.swing.JInternalFrame {
    Db conn = VariaveisGlobais.conexao;
    TableRowSorter<TableModel> sorter;

    /**
     * Creates new form jContasControle
     */
    public jContasControle() {
        initComponents();

        // Icone da tela
        FlatSVGIcon icone = new FlatSVGIcon("menuIcons/contasControle.svg",16,16);
        setFrameIcon(icone);        
        
        FillBuffer(tvbBuffer);
        jbtdelgrupo.setEnabled(false);
    }

    private void FillBuffer(JTable table) {
        // Seta Cabecario
        TableControl.header(tvbBuffer, new String[][] {{"id","Buffer"},{"0","500"}});    

        String sSql = "SELECT autoid, buffer FROM combobuffer WHERE UPPER(TRIM(local)) = 'CONTAS' ORDER BY Lower(buffer);";
        ResultSet imResult = this.conn.OpenTable(sSql, null);

        try {
            while (imResult.next()) {
                String tid = String.valueOf(imResult.getInt("autoid"));
                String tbuffer = imResult.getString("buffer").toUpperCase();

                TableControl.add(table, new String[][]{{tid, tbuffer},{"C","L"}}, true);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        conn.CloseTable(imResult);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jtbFiles = new javax.swing.JTable();
        jBuscaPasta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tvbBuffer = new javax.swing.JTable();
        txbGrupo = new javax.swing.JTextField();
        jbtdelgrupo = new javax.swing.JButton();
        tDebito = new javax.swing.JFormattedTextField();
        tCredito = new javax.swing.JFormattedTextField();
        tSaldo = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtListarConta = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Contas - Controle");
        setVisible(true);

        jtbFiles.setAutoCreateRowSorter(true);
        jtbFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbFiles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jtbFiles);

        jBuscaPasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBuscaPastaKeyReleased(evt);
            }
        });

        jLabel4.setText("Buscar:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Seleção/Criação de Contas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tvbBuffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tvbBuffer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tvbBuffer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvbBufferMouseClicked(evt);
            }
        });
        tvbBuffer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tvbBufferKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tvbBuffer);

        txbGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txbGrupoFocusLost(evt);
            }
        });
        txbGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txbGrupoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbGrupoKeyReleased(evt);
            }
        });

        jbtdelgrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/stop.png"))); // NOI18N
        jbtdelgrupo.setText("Conta:");
        jbtdelgrupo.setToolTipText("Somente é possivel excluir uma Conta quando a mesma seu saldo for ZERO...");
        jbtdelgrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdelgrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtdelgrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txbGrupo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtdelgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tDebito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        tDebito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tDebito.setText("0,00");

        tCredito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        tCredito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tCredito.setText("0,00");

        tSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        tSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tSaldo.setText("0,00");

        jLabel1.setText("Saldo da Conta:");

        jbtListarConta.setText("Listar Conta");
        jbtListarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtListarConta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBuscaPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jBuscaPasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jbtListarConta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuscaPastaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscaPastaKeyReleased
        if ("".equals(jBuscaPasta.getText().trim())) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter(jBuscaPasta.getText().trim()));
            } catch (PatternSyntaxException pse) {
                System.err.println("Bad regex pattern");
            }
        }
    }//GEN-LAST:event_jBuscaPastaKeyReleased

    private void txbGrupoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txbGrupoFocusLost
        if (tvbBuffer.getSelectedRow() > -1) {
            txbGrupo.setText(tvbBuffer.getValueAt(tvbBuffer.getSelectedRow(), 1).toString().trim());
        } else {
            if ("master".equals(VariaveisGlobais.funcao)) {
                if (!"".equals(txbGrupo.getText().trim())) {
                    String sql = "INSERT INTO combobuffer (buffer, local) VALUES ('&1.','&2.')";
                    sql = FuncoesGlobais.Subst(sql, new String[]{txbGrupo.getText().trim().toUpperCase(), "CONTAS"});
                    conn.CommandExecute(sql, null);
                    FillBuffer(tvbBuffer);
                    tvbBuffer.addRowSelectionInterval(tvbBuffer.getRowCount() - 1, tvbBuffer.getRowCount() - 1);
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione um grupo!!!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    txbGrupo.setText("");
                    txbGrupo.requestFocus();
                    return;
                }
            } else {
                if (!"".equals(txbGrupo.getText().trim())) {
                    JOptionPane.showMessageDialog(null, "Usuário não pode criar grupo!!!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    txbGrupo.setText("");
                    txbGrupo.requestFocus();
                    return;
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione um grupo!!!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    txbGrupo.setText("");
                    txbGrupo.requestFocus();
                    return;
                }
            }
        }
    }//GEN-LAST:event_txbGrupoFocusLost

    private void txbGrupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbGrupoKeyPressed

   }//GEN-LAST:event_txbGrupoKeyPressed

    private void txbGrupoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbGrupoKeyReleased
        int Pos = TableControl.seek(tvbBuffer, 1, txbGrupo.getText().toUpperCase().trim());
        if (Pos > -1) {
            tvbBuffer.addRowSelectionInterval(Pos, Pos);
        } else {
            tvbBuffer.removeRowSelectionInterval(0, tvbBuffer.getRowCount() - 1);
        }
    }//GEN-LAST:event_txbGrupoKeyReleased

    private void tvbBufferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvbBufferMouseClicked
        MoveLista();
    }//GEN-LAST:event_tvbBufferMouseClicked

    private void MoveLista() {
        txbGrupo.setText(tvbBuffer.getValueAt(tvbBuffer.getSelectedRow(), 1).toString().trim().toUpperCase());
        FillContas(tvbBuffer.getValueAt(tvbBuffer.getSelectedRow(), 0).toString().trim());        
    }
    
    private void jbtdelgrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdelgrupoActionPerformed
        if (tvbBuffer.getSelectedRow() < 0) return;
        if ("master".equals(VariaveisGlobais.funcao)) {
            String sql = "DELETE FROM combobuffer WHERE autoid = '&1.' AND local = 'CONTAS';";
            String id = tvbBuffer.getValueAt(tvbBuffer.getSelectedRow(), 0).toString().trim().toUpperCase();
            sql = FuncoesGlobais.Subst(sql, new String[] {id});
            try {conn.CommandExecute(sql);} catch (Exception ex) {}
            TableControl.del(tvbBuffer, tvbBuffer.getSelectedRow());
            jbtdelgrupo.setEnabled(false);
        }
    }//GEN-LAST:event_jbtdelgrupoActionPerformed

    private void jbtListarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListarContaActionPerformed
        String registro = tvbBuffer.getModel().getValueAt(tvbBuffer.getSelectedRow(), 0).toString();
        String query =  "SELECT a.registro, " +
                        "(SELECT b.buffer FROM combobuffer b WHERE b.autoid = a.registro) AS conta, " +
                        "(Mid(a.campo,50,3)) AS tipo, " +
                        "Cast(ConCat(Mid(a.campo,45,4),'-',Mid(a.campo,43,2),'-',Mid(a.campo,41,2)) AS Date) AS data, " +
                        "Cast(Concat(Mid(a.campo,6,8),'.',Mid(a.campo,14,2)) AS DECIMAL(19,2)) AS valor, " +
                        "Mid(a.campo,57,InStr(Mid(a.campo,57),':') - 1) AS descricao, " +
                        "Mid(Mid(a.campo,57), InStr(Mid(a.campo,57),':') + 1) AS user, " +
                        "a.autenticacao FROM avisos a WHERE a.rid = '5' AND (a.tag <> 'X' OR ISNULL(a.tag)) AND a.registro = '" + registro + "' " +
                        "ORDER BY a.registro, a.autenticacao;";
        ResultSet rs = conn.OpenTable(query, null);

        //implementação da interface JRDataSource para DataSource ResultSet
        JRResultSetDataSource jrRS = new JRResultSetDataSource( rs );

        new jDirectory("reports/Relatorios/" + Dates.iYear(new Date()) + "/" + Dates.Month(new Date()) + "/");
        String pathName = "reports/Relatorios/" + Dates.iYear(new Date()) + "/" + Dates.Month(new Date()) + "/";

        String outFileName = pathName + "ContasCtr_" + Dates.DateFormata("ddMMyyyy", new Date()) + ".pdf";
        String fileName = "reports/rContasControle.jasper";

        //executa o relatório
        Map parametros = new HashMap();
        parametros.put("registro", registro);

        try {
            /* Preenche o relatório com os dados. Gera o arquivo BibliotecaPessoal.jrprint    */
            //JasperFillManager.fillReportToFile( fileName, parametros, jrRS );
            JasperPrint print = JasperFillManager.fillReport(fileName, parametros, jrRS);

            JRExporter exporter = new JRPdfExporter();

            // Configure the exporter (set output file name and print object)
            
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, outFileName);
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);

            // Export the PDF file
            exporter.exportReport();
        
            new toPreview(outFileName);
//            if (!"jasper".equals(VariaveisGlobais.reader)) {
//                ComandoExterno ce = new ComandoExterno();
//                ComandoExterno.ComandoExterno(VariaveisGlobais.reader + " " + outFileName);
//            } else {
//                JasperViewer viewer = new JasperViewer(print, false);
//                viewer.show();
//            }

        } catch (Exception ex) {}
        conn.CloseTable(rs);
    }//GEN-LAST:event_jbtListarContaActionPerformed

    private void tvbBufferKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvbBufferKeyReleased
        MoveLista();
    }//GEN-LAST:event_tvbBufferKeyReleased

    
    private void FillContas(String sID) {
        float fTotCred = 0; float fTotDeb = 0; 
        String sql = FuncoesGlobais.Subst("SELECT campo, autenticacao FROM avisos WHERE registro = '&1.' AND rid = '5' AND (tag <> 'X' OR ISNULL(tag));", new String[] {sID});
        ResultSet hrs = conn.OpenTable(sql, null);

        TableControl.Clear(jtbFiles);
        // Seta Cabecario
        TableControl.header(jtbFiles, new String[][] {{"Data", "Descrição", "Créditos", "Débitos", "Aut"},{"80","300","100","100","50"}});

        try {
            while (hrs.next()) {
                String tmpCampo = "" + hrs.getString("campo");
                String[][] rCampos = FuncoesGlobais.treeArray(tmpCampo, false);
                String sinq = FuncoesGlobais.DecriptaNome(rCampos[0][10]);
                String sData = rCampos[0][7].substring(0, 2) + "/" + rCampos[0][7].substring(2,4) + "/" + rCampos[0][7].substring(4);
                String sAut = "" + hrs.getString("autenticacao");
                
                if (!"".equals(sinq.trim())) {
                    String aLinhas[] = WordWrap.wrap(sinq, 237, getFontMetrics(new java.awt.Font("SansSerif",Font.NORMAL,8))).split("\n");
                    for (int k=0;k<aLinhas.length;k++) {
                        String tData = ""; String tDesc = aLinhas[k].replace("ò", " "); String tCred = ""; String tDeb = ""; String tAut = "";
                        if (k != aLinhas.length - 1) { tData = ""; tCred = ""; tDeb = ""; tAut = ""; } else {
                            tData = sData; 
                            if ("CRE".equals(rCampos[0][8])) {
                                tCred = LerValor.FormatNumber(rCampos[0][2],2);
                                tDeb =  "";
                            } else {
                                tCred = "";
                                tDeb =  LerValor.FormatNumber(rCampos[0][2],2);
                            }
                            tAut = sAut;
                        }
                        TableControl.add(jtbFiles, new String[][] {{tData, tDesc, tCred, tDeb, tAut},{"C","L","R","R","C"}}, true); 
                    }
                    if ("CRE".equals(rCampos[0][8])) {
                        fTotCred += LerValor.StringToFloat(LerValor.FormatNumber(rCampos[0][2],2));
                    } else {
                        fTotDeb += LerValor.StringToFloat(LerValor.FormatNumber(rCampos[0][2],2));
                    }
                }
            }
        } catch (SQLException ex) {}
        conn.CloseTable(hrs);

        tCredito.setText(LerValor.floatToCurrency(fTotCred, 2));
        tDebito.setText(LerValor.floatToCurrency(fTotDeb, 2));
        float sld = LerValor.StringToFloat(LerValor.floatToCurrency(fTotCred,2)) - LerValor.StringToFloat(LerValor.floatToCurrency(fTotDeb, 2));
        tSaldo.setText(LerValor.floatToCurrency(sld, 2));
        
        sorter = new TableRowSorter<TableModel>(jtbFiles.getModel());
        jtbFiles.setRowSorter(sorter);
        
        jbtdelgrupo.setEnabled(sld == 0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBuscaPasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtListarConta;
    private javax.swing.JButton jbtdelgrupo;
    private javax.swing.JTable jtbFiles;
    private javax.swing.JFormattedTextField tCredito;
    private javax.swing.JFormattedTextField tDebito;
    private javax.swing.JFormattedTextField tSaldo;
    private javax.swing.JTable tvbBuffer;
    private javax.swing.JTextField txbGrupo;
    // End of variables declaration//GEN-END:variables
}
/*  SELECT 
        a.registro, 
        (SELECT b.buffer FROM combobuffer b WHERE b.autoid = a.registro) AS conta, 
        (Mid(a.campo,50,3)) AS tipo, 
        Cast(ConCat(Mid(a.campo,45,4),'-',Mid(a.campo,43,2),'-',Mid(a.campo,41,2)) AS Date) AS data,  
        Cast(Concat(Mid(a.campo,6,8),'.',Mid(a.campo,14,2)) AS DECIMAL(19,2)) AS valor,
        Mid(a.campo,57,InStr(Mid(a.campo,57),':') - 1) AS descricao,
        Mid(Mid(a.campo,57), InStr(Mid(a.campo,57),':') + 1) AS user,
        a.autenticacao 
    FROM 
        avisos a 
    WHERE 
        a.rid = '5' AND (a.tag <> 'X' OR ISNULL(a.tag)) 
    ORDER BY 
        a.registro, a.autenticacao;
*/