package Movimento;

import Funcoes.AutoCompletion;
import Funcoes.Db;
import Funcoes.FuncoesGlobais;
import Funcoes.LerValor;
import Funcoes.VariaveisGlobais;
import Sici.Partida.Collections;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.AWTKeyStroke;
import java.awt.Component;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import javax.swing.BorderFactory;
import javax.swing.ComboBoxEditor;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

public class jMultas extends javax.swing.JInternalFrame {
    Db conn = VariaveisGlobais.conexao;
    String rgprp = ""; String rgimv = ""; String contrato = ""; boolean achei = false;
    
    boolean bExecNome = false, bExecCodigo = false;

    /** Creates new form jMultas */
    public jMultas() {
        initComponents();

        // Icone da tela
        FlatSVGIcon icone = new FlatSVGIcon("menuIcons/multas.svg",16,16);
        setFrameIcon(icone);        
        
        // Colocando enter para pular de campo
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);

        FillCombos(0);
        jCodigo.setEnabled(false);
        jNome.setEnabled(false);
        try {
            LerGeral();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        AutoCompletion.enable(jCodigo);
        AutoCompletion.enable(jNome);

        ComboBoxEditor edit = jNome.getEditor();
        Component comp = edit.getEditorComponent();
        comp.addFocusListener( new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                String sql = "";

                if (jrbLoca.isSelected()) {
                    Object[][] vCampos = null;
                    try {
                        vCampos = conn.ReadFieldsTable(new String[] {"rgprp", "rgimv", "contrato"}, "locatarios", "contrato = '" + jCodigo.getSelectedItem().toString() + "'");
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    rgprp = vCampos[0][3].toString();
                    rgimv = vCampos[1][3].toString();
                    contrato = vCampos[2][3].toString();
                    sql = "SELECT * FROM multa WHERE RGPRP = '" + rgprp + "' and RGIMV = '" + rgimv + "'";
                } else {
                    rgprp = jCodigo.getSelectedItem().toString();
                    rgimv = "";
                    contrato = "";
                    sql = "SELECT * FROM multa WHERE RGPRP = '" + rgprp + "' and isnull(RGIMV)";
                }
                try {
                    Limpar();
                    LerFile(sql);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });

    }

    private void FillCombos(int tipo) {
        String stipo0 = "";
        String stipo1 = "SELECT rgprp as codigo, UPPER(nome) AS nome FROM proprietarios ORDER BY UPPER(nome);";
        String stipo2 = "SELECT contrato as codigo, UPPER(nomerazao) as nome FROM locatarios ORDER BY UPPER(nomerazao)";
        String sSql = (tipo == 0 ? stipo0 : (tipo == 1 ? stipo1 : stipo2));

        jCodigo.removeAllItems();
        jNome.removeAllItems();
        if (!sSql.isEmpty()) {
            ResultSet imResult = this.conn.OpenTable(sSql, null);

            try {
                while (imResult.next()) {
                    jCodigo.addItem(String.valueOf(imResult.getInt("codigo")));
                    jNome.addItem(imResult.getString("nome"));
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            conn.CloseTable(imResult);
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jgrupo = new javax.swing.ButtonGroup();
        jtipo = new javax.swing.ButtonGroup();
        jJuros = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jadmlblMulta = new javax.swing.JLabel();
        jadmMulta = new javax.swing.JFormattedTextField();
        jadmJuros = new javax.swing.JFormattedTextField();
        jadmlblJuros = new javax.swing.JLabel();
        jadmCorrecao = new javax.swing.JFormattedTextField();
        jadmlblCorrecao = new javax.swing.JLabel();
        jadmExpediente = new javax.swing.JFormattedTextField();
        jadmlblExpediente = new javax.swing.JLabel();
        jadmADM_Multa = new javax.swing.JCheckBox();
        jadmADM_JUROS = new javax.swing.JCheckBox();
        jadmADM_Correcao = new javax.swing.JCheckBox();
        jadmADM_Expediente = new javax.swing.JCheckBox();
        jpnMultas = new javax.swing.JPanel();
        jMultaRes = new javax.swing.JFormattedTextField();
        jMultaCom = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpnJuros = new javax.swing.JPanel();
        jPorMes = new javax.swing.JRadioButton();
        jAoMes = new javax.swing.JRadioButton();
        jlblJurPerc = new javax.swing.JLabel();
        jJurosPerc = new javax.swing.JFormattedTextField();
        jpnCorrecao = new javax.swing.JPanel();
        jCorSimples = new javax.swing.JRadioButton();
        jCorComposta = new javax.swing.JRadioButton();
        jCorLimitada = new javax.swing.JCheckBox();
        jCorLimitadaDias = new javax.swing.JFormattedTextField();
        jCorPercentual = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jlblCarMulta = new javax.swing.JLabel();
        jlblCarJuros = new javax.swing.JLabel();
        jDiasMulta = new javax.swing.JFormattedTextField();
        jDiasJuros = new javax.swing.JFormattedTextField();
        jlblCarCorrecao = new javax.swing.JLabel();
        jDiasCorrecao = new javax.swing.JFormattedTextField();
        jpnExpediente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPercExpediente = new javax.swing.JFormattedTextField();
        jExpMinimo = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jExpNome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jrbGeral = new javax.swing.JRadioButton();
        jrbLoca = new javax.swing.JRadioButton();
        jrbProp = new javax.swing.JRadioButton();
        jCodigo = new javax.swing.JComboBox();
        jNome = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jlblPerGerComissao = new javax.swing.JLabel();
        jPercComissao = new javax.swing.JFormattedTextField();
        jlblValorGerComissao = new javax.swing.JLabel();
        jValorComissao = new javax.swing.JFormattedTextField();
        jGravar = new javax.swing.JButton();
        jExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Regras de Calculos ::.");
        setFont(new java.awt.Font("Agency FB", 0, 8)); // NOI18N
        setMaximumSize(new java.awt.Dimension(642, 356));
        setMinimumSize(new java.awt.Dimension(642, 356));
        setPreferredSize(new java.awt.Dimension(642, 356));
        setRequestFocusEnabled(false);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Percentuais da Administradora"));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jadmlblMulta.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jadmlblMulta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jadmlblMulta.setText("Multa");

        jadmMulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.000"))));
        jadmMulta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jadmMulta.setText("0,000");
        jadmMulta.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jadmMulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jadmMultaKeyPressed(evt);
            }
        });

        jadmJuros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        jadmJuros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jadmJuros.setText("0,000");
        jadmJuros.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jadmJuros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jadmJurosKeyPressed(evt);
            }
        });

        jadmlblJuros.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jadmlblJuros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jadmlblJuros.setText("Juros");

        jadmCorrecao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        jadmCorrecao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jadmCorrecao.setText("0,000");
        jadmCorrecao.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jadmCorrecao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jadmCorrecaoKeyPressed(evt);
            }
        });

        jadmlblCorrecao.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jadmlblCorrecao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jadmlblCorrecao.setText("Correção");

        jadmExpediente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        jadmExpediente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jadmExpediente.setText("0,000");
        jadmExpediente.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jadmExpediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jadmExpedienteKeyPressed(evt);
            }
        });

        jadmlblExpediente.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jadmlblExpediente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jadmlblExpediente.setText("Expediente");

        jadmADM_Multa.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jadmADM_Multa.setForeground(new java.awt.Color(255, 0, 51));
        jadmADM_Multa.setToolTipText("Segue a mesma regra da [multa] GERAL.");

        jadmADM_JUROS.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jadmADM_JUROS.setForeground(new java.awt.Color(255, 0, 51));
        jadmADM_JUROS.setToolTipText("Segue a mesma regra da [multa] GERAL.");

        jadmADM_Correcao.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jadmADM_Correcao.setForeground(new java.awt.Color(255, 0, 51));
        jadmADM_Correcao.setToolTipText("Segue a mesma regra da [multa] GERAL.");

        jadmADM_Expediente.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jadmADM_Expediente.setForeground(new java.awt.Color(255, 0, 51));
        jadmADM_Expediente.setToolTipText("Segue a mesma regra da [multa] GERAL.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jadmlblMulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadmMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadmADM_Multa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadmlblJuros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadmJuros)
                .addGap(0, 0, 0)
                .addComponent(jadmADM_JUROS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadmlblCorrecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadmCorrecao)
                .addGap(0, 0, 0)
                .addComponent(jadmADM_Correcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadmlblExpediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadmExpediente)
                .addGap(0, 0, 0)
                .addComponent(jadmADM_Expediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jadmADM_Expediente)
                    .addComponent(jadmADM_Correcao)
                    .addComponent(jadmADM_JUROS)
                    .addComponent(jadmADM_Multa))
                .addGap(4, 4, 4))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jadmlblMulta)
                .addComponent(jadmMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jadmlblJuros)
                .addComponent(jadmJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jadmlblCorrecao)
                .addComponent(jadmCorrecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jadmlblExpediente)
                .addComponent(jadmExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, 618, -1));

        jpnMultas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Multas"));
        jpnMultas.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jMultaRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        jMultaRes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jMultaRes.setText("0,000");
        jMultaRes.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        jMultaCom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        jMultaCom.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jMultaCom.setText("0,000");
        jMultaCom.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel5.setText("Residêncial:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel6.setText("Comercial:");

        javax.swing.GroupLayout jpnMultasLayout = new javax.swing.GroupLayout(jpnMultas);
        jpnMultas.setLayout(jpnMultasLayout);
        jpnMultasLayout.setHorizontalGroup(
            jpnMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jMultaRes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMultaCom, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnMultasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jMultaCom, jMultaRes});

        jpnMultasLayout.setVerticalGroup(
            jpnMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMultasLayout.createSequentialGroup()
                .addGroup(jpnMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jMultaRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jMultaCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jpnMultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 117, -1, -1));

        jpnJuros.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Juros"));
        jpnJuros.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jJuros.add(jPorMes);
        jPorMes.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jPorMes.setText("Por Mes");

        jJuros.add(jAoMes);
        jAoMes.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jAoMes.setText("Ao Mes");

        jlblJurPerc.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jlblJurPerc.setText("Juros %");

        jJurosPerc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        jJurosPerc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jJurosPerc.setText("0,000");

        javax.swing.GroupLayout jpnJurosLayout = new javax.swing.GroupLayout(jpnJuros);
        jpnJuros.setLayout(jpnJurosLayout);
        jpnJurosLayout.setHorizontalGroup(
            jpnJurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnJurosLayout.createSequentialGroup()
                .addGroup(jpnJurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAoMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPorMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jlblJurPerc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jJurosPerc)
                .addContainerGap())
        );
        jpnJurosLayout.setVerticalGroup(
            jpnJurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnJurosLayout.createSequentialGroup()
                .addComponent(jPorMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAoMes))
            .addGroup(jpnJurosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnJurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblJurPerc)
                    .addComponent(jJurosPerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jpnJuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 166, -1, -1));

        jpnCorrecao.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Correção"));
        jpnCorrecao.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jtipo.add(jCorSimples);
        jCorSimples.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jCorSimples.setText("Simples");

        jtipo.add(jCorComposta);
        jCorComposta.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jCorComposta.setText("Composta");

        jCorLimitada.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jCorLimitada.setText("Limitado a");

        jCorLimitadaDias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jCorLimitadaDias.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCorLimitadaDias.setText("00");
        jCorLimitadaDias.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        jCorPercentual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        jCorPercentual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCorPercentual.setText("0,000");
        jCorPercentual.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        jLabel8.setText("%");

        javax.swing.GroupLayout jpnCorrecaoLayout = new javax.swing.GroupLayout(jpnCorrecao);
        jpnCorrecao.setLayout(jpnCorrecaoLayout);
        jpnCorrecaoLayout.setHorizontalGroup(
            jpnCorrecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCorrecaoLayout.createSequentialGroup()
                .addComponent(jCorSimples)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCorComposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCorPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCorLimitada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCorLimitadaDias, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnCorrecaoLayout.setVerticalGroup(
            jpnCorrecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCorrecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCorSimples)
                .addComponent(jCorComposta)
                .addComponent(jCorPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(jCorLimitada)
                .addComponent(jCorLimitadaDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jpnCorrecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 117, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Carências"));
        jPanel6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jlblCarMulta.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jlblCarMulta.setText("Dias Multa");

        jlblCarJuros.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jlblCarJuros.setText("Dias Juros");

        jDiasMulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jDiasMulta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jDiasMulta.setText("00");
        jDiasMulta.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        jDiasJuros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jDiasJuros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jDiasJuros.setText("00");
        jDiasJuros.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        jlblCarCorrecao.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jlblCarCorrecao.setText("Dias Correção");

        jDiasCorrecao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jDiasCorrecao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jDiasCorrecao.setText("00");
        jDiasCorrecao.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jlblCarMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDiasMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblCarCorrecao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDiasCorrecao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblCarJuros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDiasJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jDiasMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlblCarCorrecao)
                .addComponent(jDiasCorrecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlblCarJuros)
                .addComponent(jDiasJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlblCarMulta))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 166, 327, -1));

        jpnExpediente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Taxa Expediente"));
        jpnExpediente.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel13.setText("Percentual ");

        jPercExpediente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        jPercExpediente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPercExpediente.setText("0,000");
        jPercExpediente.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jPercExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPercExpedienteActionPerformed(evt);
            }
        });

        jExpMinimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jExpMinimo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jExpMinimo.setText("0,00");
        jExpMinimo.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel14.setText("Vr. Minimo");

        jExpNome.setEditable(false);
        jExpNome.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jExpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExpNomeActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel15.setText("Nome a Imprimir:");

        javax.swing.GroupLayout jpnExpedienteLayout = new javax.swing.GroupLayout(jpnExpediente);
        jpnExpediente.setLayout(jpnExpedienteLayout);
        jpnExpedienteLayout.setHorizontalGroup(
            jpnExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnExpedienteLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPercExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExpMinimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnExpedienteLayout.setVerticalGroup(
            jpnExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnExpedienteLayout.createSequentialGroup()
                .addGroup(jpnExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jExpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jExpMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jPercExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpnExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 243, 618, -1));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jgrupo.add(jrbGeral);
        jrbGeral.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jrbGeral.setSelected(true);
        jrbGeral.setText("Geral");
        jrbGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGeralActionPerformed(evt);
            }
        });

        jgrupo.add(jrbLoca);
        jrbLoca.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jrbLoca.setText("Locatário");
        jrbLoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLocaActionPerformed(evt);
            }
        });

        jgrupo.add(jrbProp);
        jrbProp.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jrbProp.setText("Proprietário");
        jrbProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPropActionPerformed(evt);
            }
        });

        jCodigo.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigoActionPerformed(evt);
            }
        });

        jNome.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbGeral)
                        .addGap(44, 44, 44)
                        .addComponent(jrbProp)
                        .addGap(48, 48, 48)
                        .addComponent(jrbLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbGeral)
                    .addComponent(jrbProp)
                    .addComponent(jrbLoca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 618, -1));

        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel10.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jlblPerGerComissao.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jlblPerGerComissao.setText("Perc. Geral de Comissáo");
        jlblPerGerComissao.setToolTipText("");

        jPercComissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        jPercComissao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPercComissao.setText("0,000");
        jPercComissao.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jPercComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPercComissaoActionPerformed(evt);
            }
        });

        jlblValorGerComissao.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jlblValorGerComissao.setText("Valor mínimo da Comissáo");

        jValorComissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jValorComissao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValorComissao.setText("0,00");
        jValorComissao.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jValorComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorComissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblPerGerComissao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPercComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblValorGerComissao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValorComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlblPerGerComissao)
                .addComponent(jPercComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlblValorGerComissao)
                .addComponent(jValorComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 211, 360, -1));

        jGravar.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jGravar.setText("Gravar");
        jGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGravarActionPerformed(evt);
            }
        });
        getContentPane().add(jGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 296, -1, -1));

        jExcluir.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jExcluir.setText("Excluir");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 296, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGeralActionPerformed
        FillCombos(0);
        jCodigo.setEnabled(false);
        jNome.setEnabled(false);
        Limpar();
        try {
            LerGeral();
        } catch (SQLException ex) {
            Limpar();
            ex.printStackTrace();
        }
        Border blackline = BorderFactory.createTitledBorder("Percentuais da Administradora");
        jPanel2.setBorder(blackline);
        jadmADM_Multa.setVisible(false);
        jadmADM_JUROS.setVisible(false);
        jadmADM_Correcao.setVisible(false);
        jadmADM_Expediente.setVisible(false);
    }//GEN-LAST:event_jrbGeralActionPerformed

    private void jrbLocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLocaActionPerformed
        FillCombos(2);
        jCodigo.setEnabled(true);
        jNome.setEnabled(true);
        jCodigo.requestFocus();
        Limpar();
        Border blackline = BorderFactory.createTitledBorder("Percentuais da Administradora - <Ctrl>+<G> - Para copiar das Regras Gerais.");
        jPanel2.setBorder(blackline);
        jadmADM_Multa.setVisible(true);
        jadmADM_JUROS.setVisible(true);
        jadmADM_Correcao.setVisible(true);
        jadmADM_Expediente.setVisible(true);
    }//GEN-LAST:event_jrbLocaActionPerformed

    private void jrbPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPropActionPerformed
        FillCombos(1);
        jCodigo.setEnabled(true);
        jNome.setEnabled(true);
        jCodigo.requestFocus();
        Limpar();
        Border blackline = BorderFactory.createTitledBorder("Percentuais da Administradora - <Ctrl>+<G> - Para copiar das Regras Gerais.");
        jPanel2.setBorder(blackline);
        jadmADM_Multa.setVisible(true);
        jadmADM_JUROS.setVisible(true);
        jadmADM_Correcao.setVisible(true);
        jadmADM_Expediente.setVisible(true);
    }//GEN-LAST:event_jrbPropActionPerformed

    private void jCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigoActionPerformed
        if (!bExecNome) {
            int pos = jCodigo.getSelectedIndex();
            if (jNome.getItemCount() > 0) {bExecCodigo = true; jNome.setSelectedIndex(pos); bExecCodigo = false;}
        }
    }//GEN-LAST:event_jCodigoActionPerformed

    private void jNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeActionPerformed
        if (!bExecCodigo) {
            int pos = jNome.getSelectedIndex();
            if (jCodigo.getItemCount() > 0) {bExecNome = true; jCodigo.setSelectedIndex(pos); bExecNome = false;}
        }
    }//GEN-LAST:event_jNomeActionPerformed

    private void jPercExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPercExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPercExpedienteActionPerformed

    private void jPercComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPercComissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPercComissaoActionPerformed

    private void jGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGravarActionPerformed
        try {
            Gravar((jrbGeral.isSelected() ? "G" : (jrbProp.isSelected() ? "P" : "L")));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jGravarActionPerformed

    private void jExpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jExpNomeActionPerformed

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        Object[] options = { "Sim", "Não" };
        int n = JOptionPane.showOptionDialog(null,
                "Deseja Excluir esta regra ? ",
                "Atenção", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (n == JOptionPane.YES_OPTION) {
            Excluir((jrbGeral.isSelected() ? "G" : (jrbProp.isSelected() ? "P" : "L")));
        }
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jValorComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorComissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorComissaoActionPerformed

    private void jadmMultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jadmMultaKeyPressed
        if ((jrbProp.isSelected() || jrbLoca.isSelected()) && evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_G) {
            String tjadmMulta = "0";
            try { tjadmMulta = LerValor.FormatNumber(conn.ReadParameters("PA_MULTA"), 3); } catch (SQLException e) {}
            jadmMulta.setText(tjadmMulta);
        }
    }//GEN-LAST:event_jadmMultaKeyPressed

    private void jadmJurosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jadmJurosKeyPressed
        if ((jrbProp.isSelected() || jrbLoca.isSelected()) && evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_G) {
            String tjadmJuros = "0";
            try { tjadmJuros = LerValor.FormatNumber(conn.ReadParameters("PA_JUROS"), 3); } catch (SQLException e) {}
            jadmJuros.setText(tjadmJuros);
        }
    }//GEN-LAST:event_jadmJurosKeyPressed

    private void jadmCorrecaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jadmCorrecaoKeyPressed
        if ((jrbProp.isSelected() || jrbLoca.isSelected()) && evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_G) {
            String tjadmCorrecao = "0";
            try { tjadmCorrecao = LerValor.FormatNumber(conn.ReadParameters("PA_CORR"), 3); } catch (SQLException e) {}
            jadmCorrecao.setText(tjadmCorrecao);
        }
    }//GEN-LAST:event_jadmCorrecaoKeyPressed

    private void jadmExpedienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jadmExpedienteKeyPressed
        if ((jrbProp.isSelected() || jrbLoca.isSelected()) && evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_G) {
            String tjadmExpediente = "0";
            try { tjadmExpediente = LerValor.FormatNumber(conn.ReadParameters("PA_TXEXP"), 3); } catch (SQLException e) {}
            jadmExpediente.setText(tjadmExpediente);
        }
    }//GEN-LAST:event_jadmExpedienteKeyPressed

    private void Excluir(String tipo) {
        String sql = "";
        if (tipo.equalsIgnoreCase("P")) {
            sql = "DELETE FROM multa WHERE rgprp = '" + rgprp + "' AND IsNull(rgimv);";            
        } else if (tipo.equalsIgnoreCase("L")) {
            sql = "DELETE FROM multa WHERE rgprp = '" + rgprp + "' AND rgimv = '" + rgimv + "';";            
        }
        if (!sql.equals("")) {
            try {conn.CommandExecute(sql); Limpar();} catch (Exception e) {}
        }
    }
    
    private void LerGeral() throws SQLException {
        Collections gVar = VariaveisGlobais.dCliente;

        String nmComissao = gVar.get("CM");
        jlblPerGerComissao.setText("Perc. Geral de " + nmComissao);
        String comissao = LerValor.FormatNumber(conn.ReadParameters("COMISSAO"), 3);
        jPercComissao.setText(comissao);

        jlblValorGerComissao.setText("Valor Geral de " + nmComissao);
        try {
            String comisvr = LerValor.FormatNumber(conn.ReadParameters("COMISVR"), 2);
            jValorComissao.setText(comisvr);
        } catch (Exception e) {jValorComissao.setText("0,00");}
                
        // Multa
        String nmMulta = gVar.get("MU");
        jadmlblMulta.setText(nmMulta);
        String admmulta = LerValor.FormatNumber(conn.ReadParameters("PA_MULTA"), 3);
        jadmMulta.setText(admmulta);

        // Juros
        String nmJuros = gVar.get("JU");
        jadmlblJuros.setText(nmJuros);
        String admjuros = LerValor.FormatNumber(conn.ReadParameters("PA_JUROS"), 3);
        jadmJuros.setText(admjuros);

        // Correção
        String nmCorrecao = gVar.get("CO");
        jadmlblCorrecao.setText(nmCorrecao);
        String admcorrecao = LerValor.FormatNumber(conn.ReadParameters("PA_CORR"), 3);
        jadmCorrecao.setText(admcorrecao);

        // Expediente
        String nmExpediente = gVar.get("EP");
        jadmlblExpediente.setText(nmExpediente);
        String admexpediente = LerValor.FormatNumber(conn.ReadParameters("PA_TXEXP"), 3);
        jadmExpediente.setText(admexpediente);

        jpnMultas.setBorder(javax.swing.BorderFactory.createTitledBorder(nmMulta));
        jpnJuros.setBorder(javax.swing.BorderFactory.createTitledBorder(nmJuros));
        jpnCorrecao.setBorder(javax.swing.BorderFactory.createTitledBorder(nmCorrecao));
        jpnExpediente.setBorder(javax.swing.BorderFactory.createTitledBorder(nmExpediente));
        jlblCarMulta.setText("Dias p/" + nmMulta);
        jlblCarJuros.setText("Dias p/" + nmJuros);
        jlblCarCorrecao.setText("Dias p/" + nmCorrecao);

        String multares = LerValor.FormatNumber(conn.ReadParameters("MULTA_RES"), 3);
        jMultaRes.setText(multares);
        String multacom = LerValor.FormatNumber(conn.ReadParameters("MULTA_COM"), 3);
        jMultaCom.setText(multacom);

        int cortipo = Integer.parseInt(conn.ReadParameters("COR_TIPO"));
        if (cortipo == 0) {
            jCorSimples.setSelected(true);
            jCorComposta.setSelected(false);
        } else {
            jCorSimples.setSelected(false);
            jCorComposta.setSelected(true);
        }

        String corperc = LerValor.FormatNumber(conn.ReadParameters("COR_CORR"), 3);
        jCorPercentual.setText(corperc);

        int corlim = Integer.parseInt(conn.ReadParameters("COR_LIM_SN"));
        jCorLimitada.setSelected(corlim > 0);

        String corlima = LerValor.FormatNumber(conn.ReadParameters("COR_LIM_A"), 0);
        jCorLimitadaDias.setText(corlima);

        String jurostipo = conn.ReadParameters("JUROS");
        if ("SIMPLES".equals(jurostipo.trim().toUpperCase())) {
            jPorMes.setSelected(true);
            jAoMes.setSelected(false);
        } else {
            jPorMes.setSelected(false);
            jAoMes.setSelected(true);
        }
        jlblJurPerc.setText(nmJuros.trim() + " %");
        String jurosperc = LerValor.FormatNumber(conn.ReadParameters("JUR_PER"), 3);
        jJurosPerc.setText(jurosperc);

        String diasmulta = LerValor.FormatNumber(conn.ReadParameters("DIA_MUL"), 0);
        jDiasMulta.setText(diasmulta);

        String diascorrecao = LerValor.FormatNumber(conn.ReadParameters("DIA_COR"), 0);
        jDiasCorrecao.setText(diascorrecao);

        String diasjuros = LerValor.FormatNumber(conn.ReadParameters("DIA_JUR"), 0);
        jDiasJuros.setText(diasjuros);

        String expperc = LerValor.FormatNumber(conn.ReadParameters("TE_PER"), 3);
        jPercExpediente.setText(expperc);

        String expminimo = LerValor.FormatNumber(conn.ReadParameters("TE_VRM"), 2);
        jExpMinimo.setText(expminimo);

        jExpNome.setText(nmExpediente);
        
        jadmADM_Multa.setVisible(false);
        jadmADM_Multa.setSelected(false);
        jadmADM_JUROS.setVisible(false);
        jadmADM_JUROS.setSelected(false);
        jadmADM_Correcao.setVisible(false);
        jadmADM_Correcao.setSelected(false);
        jadmADM_Expediente.setVisible(false);
        jadmADM_Expediente.setSelected(false);
    }

    private void Limpar() {
        Collections gVar = VariaveisGlobais.dCliente;

        String nmComissao = gVar.get("CM");
        jlblPerGerComissao.setText("Perc. Geral de " + nmComissao);
        String comissao = "0,000";
        jPercComissao.setText(comissao);

        jlblValorGerComissao.setText("Valor Geral de " + nmComissao);
        String comisvr = "0,00";
        jValorComissao.setText(comisvr);

        // Multa
        String nmMulta = gVar.get("MU");
        jadmlblMulta.setText(nmMulta);
        String admmulta = "0,000";
        jadmMulta.setText(admmulta);

        // Juros
        String nmJuros = gVar.get("JU");
        jadmlblJuros.setText(nmJuros);
        String admjuros = "0,000";
        jadmJuros.setText(admjuros);

        // Correção
        String nmCorrecao = gVar.get("CO");
        jadmlblCorrecao.setText(nmCorrecao);
        String admcorrecao = "0,000";
        jadmCorrecao.setText(admcorrecao);

        // Expediente
        String nmExpediente = gVar.get("EP");
        jadmlblExpediente.setText(nmExpediente);
        String admexpediente = "0,000";
        jadmExpediente.setText(admexpediente);

        jpnMultas.setBorder(javax.swing.BorderFactory.createTitledBorder(nmMulta));
        jpnJuros.setBorder(javax.swing.BorderFactory.createTitledBorder(nmJuros));
        jpnCorrecao.setBorder(javax.swing.BorderFactory.createTitledBorder(nmCorrecao));
        jpnExpediente.setBorder(javax.swing.BorderFactory.createTitledBorder(nmExpediente));
        jlblCarMulta.setText("Dias p/" + nmMulta);
        jlblCarJuros.setText("Dias p/" + nmJuros);
        jlblCarCorrecao.setText("Dias p/" + nmCorrecao);

        String multares = "0,000";
        jMultaRes.setText(multares);
        String multacom = "0,000";
        jMultaCom.setText(multacom);

        jCorSimples.setSelected(true);
        jCorComposta.setSelected(false);

        String corperc = "0,000";
        jCorPercentual.setText(corperc);

        int corlim = 0;
        jCorLimitada.setSelected(corlim > 0);

        String corlima = "00";
        jCorLimitadaDias.setText(corlima);

        jPorMes.setSelected(true);
        jAoMes.setSelected(false);

        jlblJurPerc.setText(nmJuros.trim() + " %");
        String jurosperc = "0,000";
        jJurosPerc.setText(jurosperc);

        String diasmulta = "00";
        jDiasMulta.setText(diasmulta);

        String diascorrecao = "00";
        jDiasCorrecao.setText(diascorrecao);

        String diasjuros = "00";
        jDiasJuros.setText(diasjuros);

        String expperc = "0,000";
        jPercExpediente.setText(expperc);

        String expminimo = "0,00";
        jExpMinimo.setText(expminimo);

        jExpNome.setText(nmExpediente);
        
        jadmADM_Multa.setSelected(false);
        jadmADM_JUROS.setSelected(false);
        jadmADM_Correcao.setSelected(false);
        jadmADM_Expediente.setSelected(false);        
    }

    private void LerFile(String sql) throws SQLException {
        ResultSet hRs = conn.OpenTable(sql, null);
        if (hRs.first()) {
            Collections gVar = VariaveisGlobais.dCliente;

            String nmComissao = gVar.get("CM");
            jlblPerGerComissao.setText("Perc. Geral de " + nmComissao);
            String comissao = LerValor.FormatNumber(hRs.getString("comissao"), 3);
            jPercComissao.setText(comissao);

            jlblValorGerComissao.setText("Valor Geral de " + nmComissao);
            try {
                String comisvr = LerValor.FormatNumber(hRs.getString("comisvr"), 2);
                jValorComissao.setText(comisvr);
            } catch (Exception ex) {jValorComissao.setText("0,00");}
            
            // Multa
            String nmMulta = gVar.get("MU");
            jadmlblMulta.setText(nmMulta);
            String admmulta = LerValor.FormatNumber(hRs.getString("pa_multa"), 3);
            jadmMulta.setText(admmulta);

            // Juros
            String nmJuros = gVar.get("JU");
            jadmlblJuros.setText(nmJuros);
            String admjuros = LerValor.FormatNumber(hRs.getString("pa_jur"), 3);
            jadmJuros.setText(admjuros);

            // Correção
            String nmCorrecao = gVar.get("CO");
            jadmlblCorrecao.setText(nmCorrecao);
            String admcorrecao = LerValor.FormatNumber(hRs.getString("pa_cor"), 3);
            jadmCorrecao.setText(admcorrecao);

            // Expediente
            String nmExpediente = gVar.get("EP");
            jadmlblExpediente.setText(nmExpediente);
            String admexpediente = LerValor.FormatNumber(hRs.getString("txexp"), 3);
            jadmExpediente.setText(admexpediente);

            jpnMultas.setBorder(javax.swing.BorderFactory.createTitledBorder(nmMulta));
            jpnJuros.setBorder(javax.swing.BorderFactory.createTitledBorder(nmJuros));
            jpnCorrecao.setBorder(javax.swing.BorderFactory.createTitledBorder(nmCorrecao));
            jpnExpediente.setBorder(javax.swing.BorderFactory.createTitledBorder(nmExpediente));
            jlblCarMulta.setText("Dias p/" + nmMulta);
            jlblCarJuros.setText("Dias p/" + nmJuros);
            jlblCarCorrecao.setText("Dias p/" + nmCorrecao);

            String multares = LerValor.FormatNumber(hRs.getString("multa_res"), 3);
            jMultaRes.setText(multares);
            String multacom = LerValor.FormatNumber(hRs.getString("multa_com"), 3);
            jMultaCom.setText(multacom);

            int cortipo = Integer.parseInt(LerValor.FormatNumber(hRs.getString("cor_tipo"), 0));
            jCorSimples.setSelected(cortipo == 0);
            jCorComposta.setSelected(cortipo > 0);

            String corperc = LerValor.FormatNumber(hRs.getString("cor_corr"), 3);
            jCorPercentual.setText(corperc);

            int corlim = Integer.parseInt(LerValor.FormatNumber(hRs.getString("cor_lim_a"), 0));
            jCorLimitada.setSelected(corlim > 0);

            String corlima = LerValor.FormatNumber(hRs.getString("cor_lim_a"),0);
            jCorLimitadaDias.setText(corlima);

            int pormes = Integer.parseInt(LerValor.FormatNumber("000000000" + hRs.getString("regra"), 0));
            jPorMes.setSelected(pormes > 0);
            jAoMes.setSelected(pormes == 0);

            jlblJurPerc.setText(nmJuros.trim() + " %");
            String jurosperc = LerValor.FormatNumber(hRs.getString("per_jur"), 3);
            jJurosPerc.setText(jurosperc);

            String diasmulta = LerValor.FormatNumber(hRs.getString("dia_mul"), 0);
            jDiasMulta.setText(diasmulta);

            String diascorrecao = LerValor.FormatNumber(hRs.getString("dia_cor"), 0);
            jDiasCorrecao.setText(diascorrecao);

            String diasjuros = LerValor.FormatNumber(hRs.getString("dia_jur"), 0);
            jDiasJuros.setText(diasjuros);

            String expperc = LerValor.FormatNumber(hRs.getString("te_per"), 3);
            jPercExpediente.setText(expperc);

            String expminimo = LerValor.FormatNumber(hRs.getString("te_vrm"), 2);
            jExpMinimo.setText(expminimo);

            jExpNome.setText(nmExpediente);
            
            boolean admADM_Multa = hRs.getBoolean("adm_multa");
            jadmADM_Multa.setSelected(admADM_Multa);

            boolean admADM_Juros = hRs.getBoolean("adm_juros");
            jadmADM_JUROS.setSelected(admADM_Juros);
            
            boolean admADM_Correcao = hRs.getBoolean("adm_correcao");
            jadmADM_Correcao.setSelected(admADM_Correcao);
            
            boolean admADM_Expediente = hRs.getBoolean("adm_expediente");
            jadmADM_Expediente.setSelected(admADM_Expediente);        

        achei = true;
        } else achei = false;
        conn.CloseTable(hRs);
    }

    private void Gravar(String aonde) throws SQLException {
        Collections gVar = VariaveisGlobais.dCliente;

        String nmComissao = gVar.get("CM");
        String PercComissao = jPercComissao.getText();
        String ValorComissao = jValorComissao.getText();

        // Multa
        String nmMulta = gVar.get("MU");
        String admmulta = jadmMulta.getText();

        // Juros
        String nmJuros = gVar.get("JU");
        String admjuros = jadmJuros.getText();

        // Correção
        String nmCorrecao = gVar.get("CO");
        String admcorrecao = jadmCorrecao.getText();

        // Expediente
        String nmExpediente = gVar.get("EP");
        String admexpediente = jadmExpediente.getText();

        String multares = jMultaRes.getText();
        String multacom = jMultaCom.getText();

        boolean CorSimples = jCorSimples.isSelected();

        String corperc = jCorPercentual.getText();

        boolean corlim = jCorLimitada.isSelected();

        String corlima = jCorLimitadaDias.getText();

        boolean PorMes = jPorMes.isSelected();

        String jurosperc = jJurosPerc.getText();

        String diasmulta = jDiasMulta.getText();

        String diascorrecao = jDiasCorrecao.getText();

        String diasjuros = jDiasJuros.getText();

        String expperc = jPercExpediente.getText();

        String expminimo = jExpMinimo.getText();

        boolean admADM_Multa = jadmADM_Multa.isSelected();
        boolean admADM_Juros = jadmADM_JUROS.isSelected();
        boolean admADM_Correcao = jadmADM_Correcao.isSelected();
        boolean admADM_Expediente = jadmADM_Expediente.isSelected();
        
        String sql = "";
        if ("G".equals(aonde)) {
            String[][] aPar = {{"PA_MULTA","TEXTO",FuncoesGlobais.GravaValores(admmulta,3)},
                {"PA_JUROS","TEXTO",FuncoesGlobais.GravaValores(admjuros,3)},
                {"PA_CORR","TEXTO",FuncoesGlobais.GravaValores(admcorrecao,3)},
                {"PA_TXEXP","TEXTO",FuncoesGlobais.GravaValores(admexpediente,3)},
                {"MULTA_RES","TEXTO",FuncoesGlobais.GravaValores(multares,3)},
                {"MULTA_COM","TEXTO",FuncoesGlobais.GravaValores(multacom,3)},
                {"COR_TIPO","NUMERICO",(CorSimples ? "0" : "1")},
                {"COR_LIM_SN","NUMERICO",(corlim ? "1" : "0")},
                {"COR_LIM_A","TEXTO",FuncoesGlobais.GravaValores(corlima,0)},
                {"COR_CORR","TEXTO",FuncoesGlobais.GravaValores(corperc,3)},
                {"DIA_MUL","TEXTO",FuncoesGlobais.GravaValores(diasmulta,0)},
                {"DIA_COR","TEXTO",FuncoesGlobais.GravaValores(diascorrecao,0)},
                {"DIA_JUR","TEXTO",FuncoesGlobais.GravaValores(diasjuros,0)},
                {"JUR_PER","TEXTO",FuncoesGlobais.GravaValores(jurosperc,3)},
                {"TE_PER","TEXTO",FuncoesGlobais.GravaValores(expperc,3)},
                {"TE_VRM","TEXTO",FuncoesGlobais.GravaValores(expminimo,2)},
                {"TXEXP","TEXTO",nmExpediente},
                {"COMISSAO","TEXTO",FuncoesGlobais.GravaValores(PercComissao,3)},
                {"COMISVR", "TEXTO",FuncoesGlobais.GravaValores(ValorComissao,2)},
                {"JUROS","TEXTO",(PorMes ? "SIMPLES" : "COMPOSTO")}};

            if (!conn.GravarMultiParametros(aPar)) {
                JOptionPane.showMessageDialog(null, "Nào foi possível realizar a gravação!!!\nTente novamente...", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else if ("P".equals(aonde)) {
            Object[][] tmp = {};
            try {
                tmp = conn.ReadFieldsTable(new String[] {"rgprp","rgimv"}, "multa", "rgprp = '" + rgprp + "' AND IsNull(rgimv)");
            } catch (Exception e) {tmp = null;}
            if (tmp == null) { achei = false; } else { achei = true; }

            String[][] aPar = {{"PA_MULTA","TEXTO",FuncoesGlobais.GravaValores(admmulta,3)},
                {"PA_JUR","TEXTO",FuncoesGlobais.GravaValores(admjuros,3)},
                {"PA_COR","TEXTO",FuncoesGlobais.GravaValores(admcorrecao,3)},
                {"TXEXP","TEXTO",FuncoesGlobais.GravaValores(admexpediente,3)},
                {"MULTA_RES","TEXTO",FuncoesGlobais.GravaValores(multares,3)},
                {"MULTA_COM","TEXTO",FuncoesGlobais.GravaValores(multacom,3)},
                {"COR_TIPO","NUMERICO",(CorSimples ? "0000000000" : "0000000001")},
                {"COR_LIM_A","TEXTO",FuncoesGlobais.GravaValores(corlima,0)},
                {"COR_CORR","TEXTO",FuncoesGlobais.GravaValores(corperc,3)},
                {"DIA_MUL","TEXTO",FuncoesGlobais.GravaValores(diasmulta,0)},
                {"DIA_COR","TEXTO",FuncoesGlobais.GravaValores(diascorrecao,0)},
                {"DIA_JUR","TEXTO",FuncoesGlobais.GravaValores(diasjuros,0)},
                {"PER_JUR","TEXTO",FuncoesGlobais.GravaValores(jurosperc,3)},
                {"TE_PER","TEXTO",FuncoesGlobais.GravaValores(expperc,3)},
                {"TE_VRM","TEXTO",FuncoesGlobais.GravaValores(expminimo,2)},
                {"TE_NOME","TEXTO",nmExpediente},
                {"COMISSAO","TEXTO",FuncoesGlobais.GravaValores(PercComissao,3)},
                {"COMISVR","TEXTO",FuncoesGlobais.GravaValores(ValorComissao,2)},
                {"REGRA","TEXTO",(PorMes ? "0" : "1")},
                {(!achei ? "rgprp" : ""),"TEXTO",rgprp},
                {"ADM_MULTA","NUMERICO",(admADM_Multa ? "1" : "0")},
                {"ADM_JUROS","NUMERICO",(admADM_Juros ? "1" : "0")},
                {"ADM_CORRECAO","NUMERICO",(admADM_Correcao ? "1" : "0")},
                {"ADM_EXPEDIENTE","NUMERICO",(admADM_Expediente ? "1" : "0")},
            };

            sql = conn.CreateSqlText2(aPar, "multa", (achei ? "rgprp = '" + rgprp + "' AND IsNull(rgimv)" : ""), (achei ? "UPDATE" : "INSERT"));
            if (conn.CommandExecute(sql) <= 0) {
                JOptionPane.showMessageDialog(null, "Nào foi possível realizar a gravação!!!\nTente novamente...", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            Object[][] tmp = {};
            try {
                tmp = conn.ReadFieldsTable(new String[] {"rgprp","rgimv"}, "multa", "rgprp = '" + rgprp + "' AND rgimv = '" + rgimv + "'");
            } catch (Exception e) {tmp = null;}
            if (tmp == null) { achei = false; } else { achei = true; }

            String[][] aPar = {{"PA_MULTA","TEXTO",FuncoesGlobais.GravaValores(admmulta,3)},
                {"PA_JUR","TEXTO",FuncoesGlobais.GravaValores(admjuros,3)},
                {"PA_COR","TEXTO",FuncoesGlobais.GravaValores(admcorrecao,3)},
                {"TXEXP","TEXTO",FuncoesGlobais.GravaValores(admexpediente,3)},
                {"MULTA_RES","TEXTO",FuncoesGlobais.GravaValores(multares,3)},
                {"MULTA_COM","TEXTO",FuncoesGlobais.GravaValores(multacom,3)},
                {"COR_TIPO","NUMERICO",(CorSimples ? "0000000000" : "0000000001")},
                {"COR_LIM_A","TEXTO",FuncoesGlobais.GravaValores(corlima,0)},
                {"COR_CORR","TEXTO",FuncoesGlobais.GravaValores(corperc,3)},
                {"DIA_MUL","TEXTO",FuncoesGlobais.GravaValores(diasmulta,0)},
                {"DIA_COR","TEXTO",FuncoesGlobais.GravaValores(diascorrecao,0)},
                {"DIA_JUR","TEXTO",FuncoesGlobais.GravaValores(diasjuros,0)},
                {"PER_JUR","TEXTO",FuncoesGlobais.GravaValores(jurosperc,3)},
                {"TE_PER","TEXTO",FuncoesGlobais.GravaValores(expperc,3)},
                {"TE_VRM","TEXTO",FuncoesGlobais.GravaValores(expminimo,2)},
                {"TE_NOME","TEXTO",nmExpediente},
                {"COMISSAO","TEXTO",FuncoesGlobais.GravaValores(PercComissao,3)},
                {"COMISVR","TEXTO",FuncoesGlobais.GravaValores(ValorComissao,2)},
                {"REGRA","TEXTO",(PorMes ? "0" : "1")},
                {(!achei ? "rgprp" : ""),"TEXTO",rgprp},
                {(!achei ? "rgimv" : ""),"TEXTO",rgimv},
                {"ADM_MULTA","NUMERICO",(admADM_Multa ? "1" : "0")},
                {"ADM_JUROS","NUMERICO",(admADM_Juros ? "1" : "0")},
                {"ADM_CORRECAO","NUMERICO",(admADM_Correcao ? "1" : "0")},
                {"ADM_EXPEDIENTE","NUMERICO",(admADM_Expediente ? "1" : "0")},
            };
        
            sql = conn.CreateSqlText2(aPar, "multa", (achei ? "rgprp = '" + rgprp + "' AND rgimv = '" + rgimv + "'" : ""), (achei ? "UPDATE" : "INSERT"));
            if (conn.CommandExecute(sql) <= 0) {
                JOptionPane.showMessageDialog(null, "Nào foi possível realizar a gravação!!!\nTente novamente...", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jAoMes;
    private javax.swing.JComboBox jCodigo;
    private javax.swing.JRadioButton jCorComposta;
    private javax.swing.JCheckBox jCorLimitada;
    private javax.swing.JFormattedTextField jCorLimitadaDias;
    private javax.swing.JFormattedTextField jCorPercentual;
    private javax.swing.JRadioButton jCorSimples;
    private javax.swing.JFormattedTextField jDiasCorrecao;
    private javax.swing.JFormattedTextField jDiasJuros;
    private javax.swing.JFormattedTextField jDiasMulta;
    private javax.swing.JButton jExcluir;
    private javax.swing.JFormattedTextField jExpMinimo;
    private javax.swing.JTextField jExpNome;
    private javax.swing.JButton jGravar;
    private javax.swing.ButtonGroup jJuros;
    private javax.swing.JFormattedTextField jJurosPerc;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField jMultaCom;
    private javax.swing.JFormattedTextField jMultaRes;
    private javax.swing.JComboBox jNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JFormattedTextField jPercComissao;
    private javax.swing.JFormattedTextField jPercExpediente;
    private javax.swing.JRadioButton jPorMes;
    private javax.swing.JFormattedTextField jValorComissao;
    private javax.swing.JCheckBox jadmADM_Correcao;
    private javax.swing.JCheckBox jadmADM_Expediente;
    private javax.swing.JCheckBox jadmADM_JUROS;
    private javax.swing.JCheckBox jadmADM_Multa;
    private javax.swing.JFormattedTextField jadmCorrecao;
    private javax.swing.JFormattedTextField jadmExpediente;
    private javax.swing.JFormattedTextField jadmJuros;
    private javax.swing.JFormattedTextField jadmMulta;
    private javax.swing.JLabel jadmlblCorrecao;
    private javax.swing.JLabel jadmlblExpediente;
    private javax.swing.JLabel jadmlblJuros;
    private javax.swing.JLabel jadmlblMulta;
    private javax.swing.ButtonGroup jgrupo;
    private javax.swing.JLabel jlblCarCorrecao;
    private javax.swing.JLabel jlblCarJuros;
    private javax.swing.JLabel jlblCarMulta;
    private javax.swing.JLabel jlblJurPerc;
    private javax.swing.JLabel jlblPerGerComissao;
    private javax.swing.JLabel jlblValorGerComissao;
    private javax.swing.JPanel jpnCorrecao;
    private javax.swing.JPanel jpnExpediente;
    private javax.swing.JPanel jpnJuros;
    private javax.swing.JPanel jpnMultas;
    private javax.swing.JRadioButton jrbGeral;
    private javax.swing.JRadioButton jrbLoca;
    private javax.swing.JRadioButton jrbProp;
    private javax.swing.ButtonGroup jtipo;
    // End of variables declaration//GEN-END:variables

}
