package Movimento;

import Funcoes.Dates;
import Funcoes.Db;
import Funcoes.TableControl;
import Funcoes.VariaveisGlobais;
import Funcoes.jTableControl;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashSet;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class RecibosEmAtrazo extends javax.swing.JInternalFrame {
    Db conn = VariaveisGlobais.conexao;
    jTableControl tabela2 = new jTableControl(true);
    
    public RecibosEmAtrazo() {
        initComponents();
        
        // Icone da tela
        FlatSVGIcon icone = new FlatSVGIcon("menuIcons/locatariosBloqueio.svg",16,16);
        setFrameIcon(icone);        
        
        // Colocando enter para pular de campo
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);

        TableControl.header(tabela, new String[][] {{"contrato","nome", "atz", "dtinicial", "dtfinal"},{"100","300","30","80","80"}});
        showTabela();
    }
    
    private void showTabela() {
        ExecutorService executor = Executors.newFixedThreadPool(1);
                
        Runnable relatorioConcluidoCallback = () -> {
            // Aqui você colocaria o código para atualizar o botão
            System.out.println("Relatório concluído. Atualizando o botão...");
        };
        
        executor.submit(() -> {                
            String query = "SELECT r.`contrato`, l.`nomerazao` `nome`, Count(r.`dtvencimento`) `atrazado`, " + 
                           "Min(`dtvencimento`) `inicial`, Max(`dtvencimento`) `final` FROM recibo r " + 
                           "INNER JOIN `locatarios` l ON r.`contrato` = l.`contrato` WHERE r.`tag` != 'X' AND " + 
                           "r.`dtvencimento` < :hoje GROUP BY r.`contrato` ORDER BY 3 DESC;";
            ResultSet rs = conn.OpenTable(query, new Object[][] {{"date", "hoje", new Date()}});

            Integer[] tam = {100,300,30,80,80};
            String[] col = {"contrato", "nome", "atz", "dtinicial", "dtfinal"};
            Boolean[] edt = {false,false,false, false, false};
            String[] aln = {"C","L","C","C","C"};
            Object[][] data = {};

            int progress = 0;
            int totalRecords = conn.RecordCount(rs);
            int currentRecord = 0; progressBar.setValue(0);
            
            try {
                while (rs.next()) {
                    Object[] dado = {
                        rs.getString("contrato"), 
                        rs.getString("nome"), 
                        rs.getInt("atrazado"),
                        Dates.DateFormata("dd-MM-yyyy", rs.getDate("inicial")),
                        Dates.DateFormata("dd-MM-yyyy",rs.getDate("final"))
                    };
                    data = tabela2.insert(data, dado);
                    
                    currentRecord++;
                    progress = (int) ((currentRecord / (double) totalRecords) * 100);
                    progressBar.setValue(progress);

                    // Adicione um pequeno atraso para demonstração
                    try { Thread.sleep(100); } catch (InterruptedException iEx) {}
                    tabela2.Show(tabela, data, tam, aln, col, edt);
                }
            } catch (SQLException sqlEx) { sqlEx.printStackTrace(); }
            conn.CloseTable(rs);

            tabela2.Show(tabela, data, tam, aln, col, edt);
        });   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        progressBar = new javax.swing.JProgressBar();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Recibimentos em Atrazos.");

        tabela.setAutoCreateRowSorter(true);
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
