package Sici;

import Funcoes.Db;
import Funcoes.LimitedTextField;
import Funcoes.VariaveisGlobais;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Objects;
import javax.swing.JOptionPane;

public class jUsuarios extends javax.swing.JInternalFrame {
    Db conn = VariaveisGlobais.conexao;
    boolean isnew = false;
    ResultSet urs = conn.OpenTable("SELECT u.f_cod, u.f_nome, u.f_funcao, u.f_cpf, " +
              "u.f_rg, u.f_ctps, u.f_end, u.f_bai, u.f_cid, u.f_est, u.f_cep, u.f_tel, " +
              "u.f_cont, u.usuario, u.senha FROM cadfun u ORDER BY Upper(u.f_nome);", ResultSet.CONCUR_UPDATABLE, null);
    
    /**
     * Creates new form jUsuarios
     */
    public jUsuarios() {
        initComponents();
        
        // Icone da tela
        FlatSVGIcon icone = new FlatSVGIcon("menuIcons/usuarios.svg",16,16);
        setFrameIcon(icone);        

        // Colocando enter para pular de campo
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
        
        //setSize(788, 281);
        //pnlogin.setSize(333, 55);
        // ler primeiro geristro
        try {
            boolean next = urs.next();
            if (next) ReadFields();
        } catch (SQLException ex) {ex.printStackTrace();}
        ReadFields();
        mNome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        mNome = new LimitedTextField(50);
        jLabel2 = new javax.swing.JLabel();
        mFuncao = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        mCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        mIdentidade = new LimitedTextField(12);
        lbCTPS_CRM = new javax.swing.JLabel();
        mCTPS_CRM = new javax.swing.JTextField();
        lbUFCRM = new javax.swing.JLabel();
        mUfCRM = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter tufcrm= new javax.swing.text.MaskFormatter("UU");
            mUfCRM = new javax.swing.JFormattedTextField(tufcrm);
        }
        catch (Exception e){
        }
        jLabel9 = new javax.swing.JLabel();
        mEndereco = new LimitedTextField(50);
        jLabel10 = new javax.swing.JLabel();
        mBairro = new LimitedTextField(25);
        jLabel11 = new javax.swing.JLabel();
        mCidade = new LimitedTextField(25);
        jLabel12 = new javax.swing.JLabel();
        mEstado = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter tEstado= new javax.swing.text.MaskFormatter("UU");
            mEstado = new javax.swing.JFormattedTextField(tEstado);
        }
        catch (Exception e){
        }
        jLabel13 = new javax.swing.JLabel();
        mCep = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        mTelefone = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        mContato = new LimitedTextField(50);
        jPanel1 = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btTras = new javax.swing.JButton();
        btFrente = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mEspecialidade = new LimitedTextField(25);
        pnlogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        mLogin = new LimitedTextField(10);
        jLabel6 = new javax.swing.JLabel();
        mSenha = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Cadastro de Usuário");
        setMaximumSize(new java.awt.Dimension(715, 251));
        setMinimumSize(new java.awt.Dimension(715, 251));
        setPreferredSize(new java.awt.Dimension(715, 251));
        setVisible(true);

        lblNome.setText("Nome:");

        mNome.setText("jTextField1");

        jLabel2.setText("Cargo:");

        mFuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "master", "ger", "caixa", "user" }));
        mFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFuncaoActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF:");

        try {
            mCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("R.G:");

        mIdentidade.setText("jTextField2");

        lbCTPS_CRM.setText("CTPS:");

        mCTPS_CRM.setText("jTextField3");

        lbUFCRM.setText("UF:");

        mUfCRM.setText("jTextField4");

        jLabel9.setText("End.:");

        mEndereco.setText("jTextField1");

        jLabel10.setText("Bai.:");

        mBairro.setText("jTextField1");

        jLabel11.setText("Cid:");

        mCidade.setText("jTextField1");

        jLabel12.setText("UF:");

        mEstado.setText("jTextField1");

        jLabel13.setText("Cep:");

        try {
            mCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setText("Telefone:");

        try {
            mTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel15.setText("Contato:");

        mContato.setText("jTextField1");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Opções ]"));

        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btTras.setText("<");
        btTras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrasActionPerformed(evt);
            }
        });

        btFrente.setText(">");
        btFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrenteActionPerformed(evt);
            }
        });

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btTras)
                .addGap(0, 0, 0)
                .addComponent(btFrente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btIncluir)
                .addComponent(btTras)
                .addComponent(btFrente)
                .addComponent(btGravar)
                .addComponent(btSair))
        );

        jLabel1.setText("Função:");

        mEspecialidade.setText(null);

        pnlogin.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Login ]"));

        jLabel5.setText("Login:");

        mLogin.setText("jTextField1");

        jLabel6.setText("Senha:");

        mSenha.setText("jPasswordField1");

        javax.swing.GroupLayout pnloginLayout = new javax.swing.GroupLayout(pnlogin);
        pnlogin.setLayout(pnloginLayout);
        pnloginLayout.setHorizontalGroup(
            pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnloginLayout.setVerticalGroup(
            pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloginLayout.createSequentialGroup()
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(mSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(lblNome)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mCep, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mContato))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(mNome, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbCTPS_CRM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mCTPS_CRM, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbUFCRM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mUfCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mEspecialidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(mNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(mFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(mIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUFCRM)
                    .addComponent(mUfCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCTPS_CRM)
                    .addComponent(mCTPS_CRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(mEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(mBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(mCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(mEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(mCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(mTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(mContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFuncaoActionPerformed
        if (mFuncao.getSelectedIndex() == 0 || mFuncao.getSelectedIndex() == 2) {
            lbCTPS_CRM.setText("CTPS:");
            lbUFCRM.setVisible(false);
            mUfCRM.setVisible(false);
            mCTPS_CRM.setSize(86, 28);
            mEspecialidade.setEditable(false);
        } else {
            lbCTPS_CRM.setText("CRM:");
            lbUFCRM.setVisible(true);
            mUfCRM.setVisible(true);
            mCTPS_CRM.setSize(165, 28);
            mEspecialidade.setEditable(true);
        }
    }//GEN-LAST:event_mFuncaoActionPerformed

    private void btTrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrasActionPerformed
        try {
            boolean previous = urs.previous();
            if (previous) ReadFields();
        } catch (SQLException ex) {}        
    }//GEN-LAST:event_btTrasActionPerformed

    private void btFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrenteActionPerformed
        try {
            boolean next = urs.next();
            if (next) ReadFields();
        } catch (SQLException ex) {ex.printStackTrace();}
    }//GEN-LAST:event_btFrenteActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        btFrente.setEnabled(false);
        btTras.setEnabled(false);
        btIncluir.setEnabled(false);
        limpatela();
        mNome.requestFocus();
        isnew = true;
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
         String checkup = checacampostela(isnew);
        if (checkup == null) {
            SaveFields(isnew);
            btFrente.setEnabled(true);
            btTras.setEnabled(true);
            btIncluir.setEnabled(true);
            mNome.requestFocus();
            isnew = false;
        } else {
            JOptionPane.showMessageDialog(this, checkup, "Atenção!!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btGravarActionPerformed

    private String checacampostela(boolean Novo) {
        String retorno= null;
        
        if (mNome.getText().trim().length() <= 0) retorno = "Campo Nome";
        if (mCpf.getText().trim().replace(".", "").replace("-", "").length() <= 0) retorno = "Campo CPF";

        if (Novo && mCpf.getText().trim().replace(".", "").replace("-", "").length() > 0) {
            Object[][] jaexiste = null;
            try {jaexiste = conn.ReadFieldsTable(new String[] {"f_cpf"}, "cadfun", "f_cpf = '" + mCpf.getText().trim() + "'");} catch (Exception e) {}
            if (jaexiste != null) {retorno = "Usuário já esta cadastrado no sistema!!!"; return retorno;}
        }
        if (retorno != null && retorno.length() > 0) retorno += " do usuário é obrigatório!!!";
        return retorno;
    }
    
    private void limpatela() {
        mEspecialidade.setText(null);
        mBairro.setText(null);
        mCTPS_CRM.setText(null);
        mCep.setText(null);
        mCidade.setText(null);
        mContato.setText(null);
        mCpf.setText(null);
        mEndereco.setText(null);
        mEstado.setText(null);
        mFuncao.setSelectedIndex(0);
        mIdentidade.setText(null);
        mNome.setText(null);
         mTelefone.setText(null);
        mUfCRM.setText(null);        

        lbCTPS_CRM.setText("CTPS:");
        lbUFCRM.setVisible(false);
        mUfCRM.setVisible(false);
        mCTPS_CRM.setSize(86, 28);
        
        // login
        mLogin.setText(null);
        mSenha.setText(null);
    }
    
    public void ReadFields() {
        limpatela();
        
        String nFicha = ""; String cdMedico = "";
        String tnome = "";
        String tfuncao = "Recepção";
        String tcpf = "";
        String trg = "";
        String tctps = "";
        String tcrmuf = "";
        String tespecialidade = "";
        String tendereco = "";
        String tbairro = "";
        String tcidade = "";
        String testado = "";
        String tcep = "";
        String ttelefone = "";
        String tcontato = "";
        
        String tlogin = "";
        String tsenha = "";
        
        try {
            try {nFicha = urs.getString("f_cod");} catch (Exception e) {}
            try {tnome = urs.getString("f_nome");} catch (Exception e) {}
            try {tfuncao = urs.getString("f_funcao").toLowerCase().trim();} catch (Exception e) {}
            try {tcpf = urs.getString("f_cpf");} catch (Exception e) {}
            try {trg = urs.getString("f_rg");} catch (Exception e) {}

            lbCTPS_CRM.setText("CTPS:");
            lbUFCRM.setVisible(false);
            mUfCRM.setVisible(false);
            mCTPS_CRM.setSize(86, 28);
            mEspecialidade.setEditable(false);

            try {cdMedico = "";} catch (Exception e) {}
            try {tctps = urs.getString("f_ctps");} catch (Exception e) {}
            try {tcrmuf = "";} catch (Exception e) {}
            tespecialidade = "";
            
            try {tendereco = urs.getString("f_end");} catch (Exception e) {}
            try {tbairro = urs.getString("f_bai");} catch (Exception e) {}
            try {tcidade = urs.getString("f_cid");} catch (Exception e) {}
            try {testado = urs.getString("f_est");} catch (Exception e) {}
            try {tcep = urs.getString("f_cep");} catch (Exception e) {}
            try {ttelefone = urs.getString("f_tel");} catch (Exception e) {}
            try {tcontato = urs.getString("f_cont");} catch (Exception e) {}
            
            try {tlogin = urs.getString("usuario");} catch (Exception e) {}
            try {tsenha = urs.getString("senha");} catch (Exception e) {}
        } catch (Exception err) {err.printStackTrace();}
        
        try {mNome.setText(tnome);} catch (Exception e) {mNome.setText(null);}
        try {mNome.setToolTipText(nFicha);} catch (Exception e) {mNome.setToolTipText(null);}
        
        try {mFuncao.getModel().setSelectedItem(tfuncao);} catch (Exception e) {mFuncao.getModel().setSelectedItem("Recepção");}
        try {mFuncao.setToolTipText(cdMedico);} catch (Exception e) {mFuncao.setToolTipText(null);}

        try {mCpf.setText(tcpf);} catch (Exception e) {mCpf.setText(null);}
        try {mIdentidade.setText(trg);} catch (Exception e) {mIdentidade.setText(null);}

        lbCTPS_CRM.setText("CTPS:");
        lbUFCRM.setVisible(false);
        mUfCRM.setVisible(false);
        mCTPS_CRM.setSize(86, 28);
        mEspecialidade.setEditable(false);
        
        try {mCTPS_CRM.setText(tctps);} catch (Exception e) {mCTPS_CRM.setText(null);}
        try {mUfCRM.setText(tcrmuf);} catch (Exception e) {mUfCRM.setText(null);}
        try {mEspecialidade.setText(tespecialidade);} catch (Exception e) {mEspecialidade.setText(null);}
                
        try {mEndereco.setText(tendereco);} catch (Exception e) {mEndereco.setText(null);}
        try {mBairro.setText(tbairro);} catch (Exception e) {mBairro.setText(null);}
        try {mCidade.setText(tcidade);} catch (Exception e) {mCidade.setText(null);}
        try {mEstado.setText(testado);} catch (Exception e) {mEstado.setText(null);}
        try {mCep.setText(tcep);} catch (Exception e) {mCep.setText(null);}
        try {mTelefone.setText(ttelefone);} catch (Exception e) {mTelefone.setText(null);}
        try {mContato.setText(tcontato);} catch (Exception e) {mContato.setText(null);}

        try {mLogin.setText(tlogin);} catch (Exception e) {mLogin.setText(null);}
        try {mSenha.setText(tsenha);} catch (Exception e) {mSenha.setText(null);}
    }
    
    private void SaveFields(boolean save) {
        String tficha = ""; try {tficha = mNome.getToolTipText();} catch (Exception e) {}
        String tnome = ""; try {tnome = mNome.getText();} catch (Exception e) {}

        String tfuncao = ""; try {tfuncao = mFuncao.getSelectedItem().toString();} catch (Exception e) {}
        String tcdmed = ""; try {tcdmed = mFuncao.getToolTipText();} catch (Exception e) {}
        
        String tcpf = ""; try {tcpf = mCpf.getText();} catch (Exception e) {}
        String trg = ""; try {trg = mIdentidade.getText();} catch (Exception e) {}
        String tctps = ""; try {tctps = mCTPS_CRM.getText();} catch (Exception e) {}
        String tcrmuf = ""; try {tcrmuf = mUfCRM.getText();} catch (Exception e) {}
        String tespecialidade = ""; try {tespecialidade = mEspecialidade.getText();} catch (Exception e) {}
        String tendereco = ""; try {tendereco = mEndereco.getText();} catch (Exception e) {}
        String tbairro = ""; try {tbairro = mBairro.getText();} catch (Exception e) {}
        String tcidade = ""; try {tcidade = mCidade.getText();} catch (Exception e) {}
        String testado = ""; try {testado = mEstado.getText();} catch (Exception e) {}
        String tcep = ""; try {tcep = mCep.getText();} catch (Exception e) {} 
        String ttelefone = ""; try {ttelefone = mTelefone.getText();} catch (Exception e) {}
        String tcontato = ""; try {tcontato = mContato.getText();} catch (Exception e) {}
        
        String tlogin = ""; try {tlogin = mLogin.getText();} catch (Exception e) {}
        String tsenha = ""; try {tsenha = mSenha.getText();} catch (Exception e) {}

        String sql;
        if (save) {
            try {
                tficha = String.valueOf(Integer.valueOf(conn.ReadParameters("codfun")) + 1).replace(".0", "");
                conn.SaveParameters(new String[] {"codfun",tficha,"NUMERICO"});
            } catch (Exception e) {}
            
            try {
                sql = "INSERT INTO cadfun(" +
                "f_cod, f_nome, f_funcao, f_cpf, f_rg, f_ctps, f_end, f_bai, f_cid, f_est, " +
                "f_cep, f_tel, f_cont, usuario, senha) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

                PreparedStatement stm = conn.conn.prepareStatement(sql);
                // coloca os campos
                stm.setString(1, tficha);
                stm.setString(2, tnome);
                stm.setString(3, tfuncao);
                stm.setString(4, tcpf);
                stm.setString(5, trg);
                stm.setString(6, tctps);
                stm.setString(7, tendereco);
                stm.setString(8, tbairro);
                stm.setString(9, tcidade);
                stm.setString(10, testado);
                stm.setString(11, tcep);
                stm.setString(12, ttelefone);
                stm.setString(13, tcontato);
                stm.setString(14, tlogin);
                stm.setString(15, tsenha);
                stm.execute();
                stm.close();
            } catch (Exception err) {err.printStackTrace();}
        } else {
            try {
                sql = "UPDATE cadfun " +
                "SET f_cod=?, f_nome=?, f_funcao=?, f_cpf=?, f_rg=?, f_ctps=?, f_end=?, f_bai=?, " +
                "f_cid=?, f_est=?, f_cep=?, f_tel=?, f_cont=?, usuario=?, senha=? WHERE f_cod = ?;";

                PreparedStatement stm = conn.conn.prepareStatement(sql);
                
                // coloca os campos
                stm.setString(1, tficha);
                stm.setString(2, tnome);
                stm.setString(3, tfuncao);
                stm.setString(4, tcpf);
                stm.setString(5, trg);
                stm.setString(6, tctps);
                stm.setString(7, tendereco);
                stm.setString(8, tbairro);
                stm.setString(9, tcidade);
                stm.setString(10, testado);
                stm.setString(11, tcep);
                stm.setString(12, ttelefone);
                stm.setString(13, tcontato);
                stm.setString(14, tlogin);
                stm.setString(15, tsenha);
                stm.setString(16, tficha);
                stm.execute();
                stm.close();
            } catch (Exception err) {err.printStackTrace();}
        }

        conn.CloseTable(urs);
        urs = conn.OpenTable("SELECT u.f_cod, u.f_nome, u.f_funcao, u.f_cpf, " +
                      "u.f_rg, u.f_ctps, u.f_end, u.f_bai, u.f_cid, u.f_est, u.f_cep, u.f_tel, " +
                      "u.f_cont, u.usuario, u.senha FROM cadfun u ORDER BY Upper(u.f_nome);", ResultSet.CONCUR_UPDATABLE, null);        

        // ler primeiro geristro
        try {
            boolean next = urs.next();
            if (next) ReadFields();
        } catch (SQLException ex) {ex.printStackTrace();}
        ReadFields();
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFrente;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btTras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCTPS_CRM;
    private javax.swing.JLabel lbUFCRM;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField mBairro;
    private javax.swing.JTextField mCTPS_CRM;
    private javax.swing.JFormattedTextField mCep;
    private javax.swing.JTextField mCidade;
    private javax.swing.JTextField mContato;
    private javax.swing.JFormattedTextField mCpf;
    private javax.swing.JTextField mEndereco;
    private javax.swing.JTextField mEspecialidade;
    private javax.swing.JTextField mEstado;
    private javax.swing.JComboBox mFuncao;
    private javax.swing.JTextField mIdentidade;
    private javax.swing.JTextField mLogin;
    private javax.swing.JTextField mNome;
    private javax.swing.JPasswordField mSenha;
    private javax.swing.JFormattedTextField mTelefone;
    private javax.swing.JTextField mUfCRM;
    private javax.swing.JPanel pnlogin;
    // End of variables declaration//GEN-END:variables
}
